### ISSUE TITLE
Cannot find namespace 'React' - ReactEmail/Render

### ISSUE THREAD

**Issue by virtualstoodeeoh-dev** [resend/react-email#1049]
### Describe the Bug

I keep on getting this error when I am trying to build my files:

node_modules/.pnpm/@react-email+render@0.0.9/node_modules/@react-email/render/dist/index.d.ts:5

The package seems to work well if I am just running using Nodemon but when I am building it, it doesn't work.

I have tried downgrading react, removing node modules, and reinstalling.

To keep note of: When I reinstalled packages and removed the pnpm lockfile. For some reason react was not part of the package.json automatically and I had to add it again.

Please advise.

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

It's very hard to reproduce given it's an old codebase.

### To Reproduce

Install react email and set everything up
Install react email / render afterwards
Use SendGrid to send an email using the render method

Typescript settings:
`{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "target": "ESNext",
    "sourceMap": true,
    "outDir": "dist",
    "jsx": "react-jsx"
  },
  "include": ["src/**/*"],
  "ts-node": {
    "esm": true
  }
}
`

### Expected Behavior

To build properly!

### What's your node version? (if relevant)

19.8.1

**Comment by gabrielmfern** [comment]
Is this an error you get with the export command? I couldn't follow what you said completely, if so, can you try out the latest version?

**Comment by gabrielmfern** [comment]
Closing this as stale, if someone has this issue I'll reopen it.
