### ISSUE TITLE
Doesn't work with ESM typescript files

### ISSUE THREAD

**Issue by janek515** [resend/react-email#1051]
### Describe the Bug

I'm building an app in typescript and I'm using ESM `"type":"module"`. This means that all my imports use explicit file extension `.js` which is not the de facto extension of the source files. When trying to import anything from my codebase errors occur.
![image](https://github.com/resendlabs/react-email/assets/37900649/b8db0558-8023-4b5b-9afe-d86bc91dc01e)

### Link to the code that reproduces this issue

n/a

### To Reproduce

1. create a project
2. set type to module in package.json
3. add an import to external file in the email file

### Expected Behavior

everything works

**Comment by florianbepunkt** [comment]
Same issue here. Beautiful library, but ESM users are left out unfortunately.

@gabrielmfern  I created a self contained repro for this issue here: https://github.com/florianbepunkt/react-emails-esm-repro

**Comment by gabrielmfern** [comment]
@florianbepunkt Thanks for the repro, but it seems to maybe be private 🤔

**Comment by florianbepunkt** [comment]
@gabrielmfern Made it public now, apologies. This should have been fixed in Next.js – not sure why the issue still exists: https://github.com/vercel/next.js/issues/41961

**Comment by gabrielmfern** [comment]
This should now be fixed as the preview server is completely different and bundles the emails using esbuild
