### ISSUE TITLE
esm compatiblity issue on `react-email` with `strip-ansi`

### ISSUE THREAD

**Issue by pepsiamir** [resend/react-email#1075]
### Describe the Bug

`
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\reps\react-email-starter\node_modules\strip-ansi\index.js from D:\reps\react-email-starter\node_modules\ora\index.js not supported.
Instead change the require of D:\reps\react-email-starter\node_modules\strip-ansi\index.js in D:\reps\react-email-starter\node_modules\ora\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\reps\react-email-starter\node_modules\ora\index.js:7:19)
    at Object.<anonymous> (D:\reps\react-email-starter\node_modules\react-email\dist\source\utils\generate-email-preview.js:10:31)
    at Object.<anonymous> (D:\reps\react-email-starter\node_modules\react-email\dist\source\utils\index.js:20:14)
    at Object.<anonymous> (D:\reps\react-email-starter\node_modules\react-email\dist\source\commands\dev.js:7:17)    
    at Object.<anonymous> (D:\reps\react-email-starter\node_modules\react-email\dist\source\index.js:8:15) {
  code: 'ERR_REQUIRE_ESM'
}
`

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email

### To Reproduce

`
{
  "name": "emails",
  "version": "0.0.18",
  "scripts": {
    "dev": "email dev",
    "export": "email export"
  },
  "dependencies": {
    "@react-email/components": "0.0.6",
    "react-email": "1.9.3"
  }
}`

### Expected Behavior

The development server doesn't start

### What's your node version? (if relevant)

18.17.1

**Comment by e-willits** [comment]
can confirm this happened in my project as well, cannot run tests to complete github action

**Comment by atadeuccislideworks** [comment]
First time running `email dev` the server started fine, on the second try I also got this error.

Deleting node_modules and reinstalling didn't fix it

**Comment by gabrielmfern** [comment]
@atadeuccislideworks That's interesting, could you give a reproduction so I can test it and maybe find out what's wrong in your situation? This shouldn't be happening and I'll work on a fix for it

**Comment by atadeuccislideworks** [comment]
> @atadeuccislideworks That's interesting, could you give a reproduction so I can test it and maybe find out what's wrong in your situation? This shouldn't be happening and I'll work on a fix for it

I'll try to reproduce

**Comment by atadeuccislideworks** [comment]
@gabrielmfern yeah, unfortunately I wasn't able to reproduce consistently the issue, managed once in a new folder, then couldn't make it happen again and I tried a bunch, it's one of those weird ones. One issue that always happened was #977. Thanks anyway ✌

**Comment by tominek** [comment]
I have the same issue, first time after install it works and on second run it stops working. Tried both node versions 18 and 20 - without difference.

**Comment by in19farkt** [comment]
I also get this error when creating the project from template.

## Steps to reproduce:

1. environment:
    - node: v18.19.0
    - npm: 9.9.2
    - yarn: 1.22.17
2. run `npx create-email@0.0.20`
3. run `cd ./react-email-starter`
4. run `yarn`
5. run `yarn dev` and wait for the dev server to start
6. press `Ctrl + C`
7. run `yarn dev` or `yarn export`
8. look at the error in the terminal 🤔

## Steps to resolve issue:

1. open terminal in `react-email-starter` folder
2. remove all previously installed dependencies using `rm -rf ./node_modules ./.react-email`
3. go to `package.json` and remove the workspaces configuration
    ```diff
    {
      "name": "emails",
      "version": "0.0.18",
      "private": true,
    - "workspaces": [
    -   ".react-email"
    - ],
      "scripts": {
        "dev": "email dev",
        "export": "email export"
      },
      "dependencies": {
        "@react-email/components": "0.0.12",
        "react-email": "1.10.0"
      }
    }
    ```
4. run `yarn`
5. run `yarn dev` and wait for the dev server to start
6. press `Ctrl + C`
7. run `yarn dev` or `yarn export`
8. enjoy 😉

**Comment by jinsley8** [comment]
See comment regarding a bug with yarn: https://github.com/resend/react-email/issues/1130#issuecomment-1895008128

**Comment by gabrielmfern** [comment]
Closing this as it is an issue with yarn, https://github.com/eslint/eslint/discussions/17215#discussioncomment-6511704.
