### ISSUE TITLE
Cannot setup up project with manual setup

### ISSUE THREAD

**Issue by skanaar** [resend/react-email#1076]
### Describe the Bug

When I follow the **Manual setup** guide to the letter I get this error when running `npm run dev`:

```
Error: EEXIST: file already exists, mkdir '.react-email-temp'
    at Object.mkdirSync (node:fs:1379:3)
    at /Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:61:35
    at step (/Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:33:23)
    at Object.next (/Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:14:53)
    at fulfilled (/Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '.react-email-temp'
}
```

### Link to the code that reproduces this issue

https://react.email/docs/getting-started/manual-setup

### To Reproduce

Follow this guide: https://react.email/docs/getting-started/manual-setup

At the second to last step it crashes:
> npm run dev

### Expected Behavior

I expect the guide to let me start a development server previewing the example email react component.

### What's your node version? (if relevant)

20.9.0

**Comment by bick** [comment]
@skanaar Have you tried running `npm cache clean --force`? Also, please try deleting your `node_modules` folder and running `npm install`.

**Comment by gabrielmfern** [comment]
> ### Describe the Bug
> 
> When I follow the **Manual setup** guide to the letter I get this error when running `npm run dev`:
> 
> ```
> Error: EEXIST: file already exists, mkdir '.react-email-temp'
>     at Object.mkdirSync (node:fs:1379:3)
>     at /Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:61:35
>     at step (/Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:33:23)
>     at Object.next (/Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:14:53)
>     at fulfilled (/Users/kallin/git/babyshop/react-email-starter/node_modules/react-email/dist/source/utils/download-client.js:5:58)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   errno: -17,
>   syscall: 'mkdir',
>   code: 'EEXIST',
>   path: '.react-email-temp'
> }
> ```
> 
> ### Which package is affected (leave empty if unsure)
> 
> _No response_
> ### Link to the code that reproduces this issue
> 
> https://react.email/docs/getting-started/manual-setup
> ### To Reproduce
> 
> Follow this guide: https://react.email/docs/getting-started/manual-setup
> 
> At the second to last step it crashes:
> 
> > npm run dev
> 
> ### Expected Behavior
> 
> I expect the guide to let me start a development server previewing the example email react component.
> ### What's your node version? (if relevant)
> 
> 20.9.0

Couldn't reproduce, can you take a look into your environment? This is probably an issue at that level.

**Comment by raulclaudino** [comment]
I have the same problem.

Yarn version: 1.22.19
Node version: 20.10.0 or 21.3.0
MacOS ARM64

**Comment by lpite** [comment]
same
yarn 1.22.21
node 21.3.0
macos 12.7.1

**Comment by gabrielmfern** [comment]
This should not happen with 2.0.0 as it is a completely different structure.
