### ISSUE TITLE
output HTML generated is not clean

### ISSUE THREAD

**Issue by GorvGoyl** [resend/react-email#1082]
### Describe the Bug

When I copy the HTML from the source, it adds invisible characters as shown below:

![screenshot 2023-12-07 at 15 32 36@2x](https://github.com/resendlabs/react-email/assets/7106086/4749826b-340e-453e-b752-48b6ab7342cd)

![screenshot 2023-12-07 at 15 33 00@2x](https://github.com/resendlabs/react-email/assets/7106086/77bbda73-ff34-4d3e-bcb4-f7f75d55bb4d)

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

na

### To Reproduce

copy paste html in a text editor like vscode

### Expected Behavior

output html should be clean.

**Comment by gabrielmfern** [comment]
This is intentional, this is to fill the remaining characters for the Email's preview with white spaces. If we don't have this the remaining characters might be characters from the actual email and not the ones you are actually expecting.
