### ISSUE TITLE
`email dev` fails to fetch tarball

### ISSUE THREAD

**Issue by rodrigoborgesdeoliveira** [resend/react-email#1097]
### Describe the Bug

After bootstrapping the example using `npx create-email@latest` and following the instructions [here](https://react.email/docs/getting-started/automatic-setup), running `npm run dev` fails with

```
RequestError [HttpError]: fetch failed
    at /Users/rodrigo/Developer/test-react-email/react-email-starter/node_modules/@octokit/request/dist-node/index.js:146:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/resendlabs/react-email/tarball/v0.0.14',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.7 octokit-core.js/4.2.4 Node.js/18.13.0 (darwin; arm64)'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

### Link to the code that reproduces this issue

https://github.com/rodrigoborgesdeoliveira/react-email-cli-bug-demo

### To Reproduce

From the provided GitHub repository, run `npm run dev`. 

### Expected Behavior

A local server running on port 3000 should start up.

### What's your node version? (if relevant)

18.13.0

**Comment by gabrielmfern** [comment]
This seems like a temporary server issue with github, can you try again?

**Comment by rodrigoborgesdeoliveira** [comment]
Still happening on my end. If I paste https://api.github.com/repos/resendlabs/react-email/tarball/v0.0.14 on the browser, it downloads the tarball just fine. I'll try with `npm run dev` later. Thanks, @gabrielmfern.

**Comment by guenhter** [comment]
Same error happens also on my side.

**Comment by robertt** [comment]
Getting this too - opening the url in my browser (& running in a http client) works fine.

**Comment by robertt** [comment]
As a temporary fix for everyone: extract the tarball and move the `client` folder into a `.react-email` folder in the root of your package using. `dev` will start working again.

**Comment by fvaldes33** [comment]
Still not working for me...

```shell
 franco@francos-mbp  ~/Projects/Sandbox/react-email-starter  npm run dev
Debugger attached.

> emails@0.0.18 dev
> email dev

Debugger attached.
✔ Emails preview generated
[Error: ENOENT: no such file or directory, open '/Users/franco/Projects/Sandbox/react-email-starter/.react-email/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/franco/Projects/Sandbox/react-email-starter/.react-email/package.json'
}
```

And I don't see that package.json file anywhere at the root of the tarball download

**Comment by gabrielmfern** [comment]
@fvaldes33 It seems to me you're having #697 now

**Comment by ThatOneAwkwardGuy** [comment]
Is is solved if you use Node 20 for some reason

**Comment by rodrigoborgesdeoliveira** [comment]
I did some tests and can confirm node 20 fixes it. For node 18, it is failing at https://github.com/resend/react-email/blob/fb7376398deb687eed13c041e1490da356395534/packages/react-email/source/utils/download-client.ts#L9-L13

I thought maybe the issue could be with octokit, but it is working with other repositories such as

```typescript
const downloadRes = await octokit.repos.downloadTarballArchive({ 
   owner: 'apple', 
   repo: 'app-store-server-library-node', 
   ref: 'main', 
 }); 
```
