### ISSUE TITLE
Vite React - ReferenceError: Cant't find variable process

### ISSUE THREAD

**Issue by Jerunnon** [resend/react-email#1115]
### Describe the Bug

When I import Resend and use const resend = new Resend(import.meta.env.VITE_RESEND_API_KEY)

I get the error ReferenceError: Can't find variable process. 

I am using latest Vite-react version.
Problem only appears when initiating Resend(). Why is that and how can I fix that?

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vitejs-vite-kn625g?file=src%2FApp.tsx

### To Reproduce

https://stackblitz.com/edit/vitejs-vite-kn625g?file=src%2FApp.tsx

the problem is in resend.js line 19 and 20. I am surprised that this issue is not appearing in next.js 18 since they also switched to import.meta.env instead of process.env.

This needs an update!!

### Expected Behavior

No errors when using Resend in Vite React.

**Comment by gabrielmfern** [comment]
Why did you close the issue? Were you able to fix it?

**Comment by Jerunnon** [comment]
No because I was told it’s the wrong repo for that issue.
