### ISSUE TITLE
Impossible to style the <tr/> element for consistent column and row rendering.

### ISSUE THREAD

**Issue by Simon-Piquemal** [resend/react-email#1125]
### Describe the Bug

When adding row and column components, the styling effects used to properly position the various columns aligned with the elements inside do not work. This issue is due to an automatically added element, which cannot be modified.

### Which package is affected (leave empty if unsure)

@react-email/column, @react-email/row

### Link to the code that reproduces this issue

////

### To Reproduce

          <Row style={{display:'flex', flexDirection:'row', gap:'8px', height:'48px', width:'100%'}}>
            <Column  style={{ width: '48px' }}>
              <Img
                src={`image.jpg`}
                width="48"
                height="48"
              />
            </Column>

            <Column
              style={{ display: 'flex', gap: '4px', flexDirection: 'column', justifyContent:'center', height:'48px'}}>
              <Text style={{ color:'#272424', fontWeight: '600',  margin:'0px', fontFamily:'sans-serif', fontSize:'16px', lineHeight:'16px'}}>
                John Doe
              </Text>
              <Text style={{color:'#5D5B5B', margin:'0px', fontFamily:'sans-serif', fontSize:'12px', lineHeight:'12px'}}>
                Doe@Doe.com
              </Text>
            </Column>

            <Column
              style={{ display: 'flex', flexDirection:'row', gap: '4px', justifyContent:'center', width:'4px', height:'48px' }}>
            </Column>

            <Column
              style={{ display: 'flex', flexDirection:'row', gap: '4px', justifyContent:'center', width:'max-content', height:'48px' }}>
                <Text style={{ color:'#272424', fontWeight: '600',  margin:'0px', fontFamily:'sans-serif', fontSize:'16px', lineHeight:'16px'}}>
                  other
                  </Text>
            </Column>
            </Row>

### Expected Behavior

The desired result:
<img width="408" alt="Capture d’écran 2024-01-04 à 15 46 11" src="https://github.com/resend/react-email/assets/36130843/da64beb0-e5e6-4d80-8fdc-224098c45466">

**Comment by gabrielmfern** [comment]
Why did you close this one?
