### ISSUE TITLE
Authors tag in intro page not highlighted

### ISSUE THREAD

**Issue by Sahillather002** [resend/react-email#1129]
### Describe the Bug

Authors tag should be highlighted .
https://github.com/resend/react-email/assets/72077931/458965d3-6527-477e-9e0d-5cb72c1ce19f

### Link to the code that reproduces this issue

https://react.email/docs/introduction#authors

### To Reproduce

Try to scroll to authors in intro

### Expected Behavior

Author tag should be highlighted or need to be corrected the behaviour.

**Comment by gabrielmfern** [comment]
The support doesn't do it either, I don't think this is something we can fix though. This is something related to mintlify.
