### ISSUE TITLE
Use Style Object to set font-family will not work in MacOS outlook

### ISSUE THREAD

**Issue by PeterChen1997** [resend/react-email#1131]
### Describe the Bug

I set this at body's style: font-family: 'PingFang SC';

After escape the  style string, the string will become: font-family: \&#x27;PingFang SC\&#x27;

And this style won't work in MacOS Outlook, It will fallback to the default font.

![image](https://github.com/resend/react-email/assets/21072589/57644bdc-190b-47c7-b07e-7e364177da0c)

But If I restore the escaped string, it works

![image](https://github.com/resend/react-email/assets/21072589/c443cf07-73e0-44e2-b827-3f2560e8fada)

How can I fix this issue 🤔 thx

### Link to the code that reproduces this issue

As the imgs show

### To Reproduce

As the imgs show

### Expected Behavior

The font-family was set properly

**Comment by PeterChen1997** [comment]
```tsx
        <style
          dangerouslySetInnerHTML={{
            __html:
              "html {font-family:'PingFang SC', 'SF Pro Display', -apple-system, BlinkMacSystemFont, 'Segoe UI',Roboto, 'Helvetica Neue', Arial, sans-serif,'Apple Color Emoji', 'Segoe UI Emoji','Segoe UI Symbol', 'Noto Color Emoji'}",
          }}
        />
```

I got it. It needs setHTML to set the value... It would be nice to add it in doc.

I can add the description in doc if needed

**Comment by gabrielmfern** [comment]
You could also use our Font component that will handle this and make things a bit simpler in your code.
