### ISSUE TITLE
Failed to compile the app 

### ISSUE THREAD

**Issue by kriptonian1** [resend/react-email#1133]
### Describe the Bug

Initially when I started the app it was working perfectly fine, and then after a restart when I tried to start the application I got this error
![image](https://github.com/resend/react-email/assets/74916308/4a4da74e-3ad1-40c2-a8d5-6629e2431441)

### Link to the code that reproduces this issue

it's a private repo

### To Reproduce

I don't really know previously it was working fine and then this happened

### Expected Behavior

It was supposed to show me the preview page

### What's your node version? (if relevant)

components -> 0.0.12 and render -> 0.0.10

**Comment by gabrielmfern** [comment]
This is an issue with the CLI, what's the version you are using of the `react-email` package? It is one that provides the preview server

**Comment by gabrielmfern** [comment]
Closing this as its most likely been solved with `react-email@2.0.0`. Feel free to re-open if you still have this.
