### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by nicitaacom** [resend/react-email#1150]
### Describe the Bug

Warning: Each child in a list should have a unique "key" prop.

When I run this code
```ts
 useEffect(() => {
    async function renderEmail() {
      const emailMessageString = await renderAsync(<CheckEmail deliveryDate={deliveryDate} />, {
        pretty: true,
      })
      setEmailMessageString(emailMessageString)
    }
    renderEmail()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  ```

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

https://github.com/nicitaacom/acc2-send-email-react-email-resend
if it ask you about .env - fill random value - in .env.local

### To Reproduce

1. `git clone https://github.com/nicitaacom/acc2-send-email-react-email-resend`
2. `pnpm i`
3. `pnpm dev`
4. Open dev tools
5. See error

### Expected Behavior

I wait no error
I got error

**Comment by nicitaacom** [comment]
Similar issue to this
https://github.com/resend/react-email/issues/1111

**Comment by nicitaacom** [comment]
How work going on this issue?

**Comment by twlite** [comment]
Hey I just stumbled upon this issue too. I am also using `renderAsync` as I want more concurrency on a backend application.

Since I do not see any concrete solutions for this, is synchronous rendering is the only workaround for this? I tried to look for `log` or `loglevel` option or something similar but could not find any :confused:

**Comment by gabrielmfern** [comment]
@twlite This is a pretty good way to silence React's key warnings when you need to https://github.com/danneu/react-template-render/commit/8ae09d53a2ae879adcb4994689fed23086b8e254

**Comment by leonardopliski** [comment]
Any updates on this? Or can we switch to another rendering engine? I'm seeing this issue with `render` and `renderAsync` too

**Comment by nicitaacom** [comment]
The same for me

Seems like the best solution for now its just use `style={{}}` instead of `@react-email/tailwind`

**Comment by nicitaacom** [comment]
> Hope this is helpful - and thank you for an awesome project!!

Thank you for fix - that work for me
![image](https://github.com/resend/react-email/assets/39565703/7437fc7c-c2fe-4e6c-a1eb-04bd64db9098)

Waiting until @geekbleek add `<Fragment/>` in `<Tailwind/>` to fix this issue

**Comment by raiyansarker** [comment]
> For anyone running into this issue, I looked into the reason the suggested fixes from @gabrielmfern work ( [facebook/react#14374 (comment)](https://github.com/facebook/react/issues/14374#issuecomment-461881546) and [danneu/react-template-render@8ae09d5](https://github.com/danneu/react-template-render/commit/8ae09d53a2ae879adcb4994689fed23086b8e254) ). They just wrap the un-keyed elements as children of a new parent element that is not expected to be a list or array of keyed elements. Most of those suggestions are a little out of date, and a newer simple way to do the same is readily available (and probably used regularly by us all) which is `<Fragment>` . I gave it a shot and it appears to have solved the issue. Psuedo code:
> 
> ```js
> <Tailwind>
>         <Fragment>
>         (...templateHere)
>         </Fragment>
> </Tailwind>
> ```
> 
> Easy fix and enables static template rendering server side with the react-email framework - much better than handlebars / moustache etc!
> 
> Hope this is helpful - and thank you for an awesome project!!

I am having this issue, `To use responsive styles you must have a <head> element as a direct child of the Tailwind component.`

**Comment by ffiona** [comment]
Too bad the issue is closed now. I would prefer the warning to be silenced in the react.email. This fix **won't work** if you use Tailwind media quires classes. It's for desktop-only markup. @raiyansarker was right and it IS related issue. The OP just didn't need mobile versions for their emails.

**Comment by ffiona** [comment]
@raiyansarker I have it the same way, but it didn't solve the issue for me, I still have the warning:

```
return (
    <Tailwind
      config = {CustomTailwindConfig}>

      <Head />

      <Fragment>

        <Preview>{preview}</Preview>

        <Body
          className="bgColor-body">
```

It works only if I put `<Head />` inside the `<Fragment>`.

**Comment by raiyansarker** [comment]
can you put the html component? it is weird tbh!!

**Comment by nicitaacom** [comment]
> @raiyansarker I have it the same way, but it didn't solve the issue for me, I still have the warning:
> 
> ```
> return (
>     <Tailwind
>       config = {CustomTailwindConfig}>
> 
>       <Head />
> 
>       <Fragment>
> 
>         <Preview>{preview}</Preview>
> 
>         <Body
>           className="bgColor-body">
> ```
> 
> It works only if I put `<Head />` inside the `<Fragment>`.

So put `<Head />` inside the `<Fragment>`.
What's the problem?

Breakpoints? - send quick video where you show when breakpoints work and when it doesn't

**Comment by ffiona** [comment]
> breakpoints doesn't work in emails

They do work, and they are generated perfectly fine by react.email out of the box:

![Screenshot 2024-03-12 at 12 31 35](https://github.com/resend/react-email/assets/1404938/ae981db6-6ef5-415b-bec2-d6e8469eba8a)

> So put Head inside the Fragment.
> What's the problem?

The problem is when you personally don't need some functionality, it doesn't mean it isn't used by everyone else. The fix worked for your case, but it has limitation and it's not an ultimate one.

> Breakpoints? - send quick video where you show when breakpoints work and when it doesn't

You can do the math by yourself. Full support of Apple devices gives a big number of potential customers.

![Screenshot 2024-03-12 at 12 36 21](https://github.com/resend/react-email/assets/1404938/653d2b13-72d7-44cf-b1db-d8cb478cb2ab)
