### ISSUE TITLE
Consider migrating off unmaintained `tree-cli`

### ISSUE THREAD

**Issue by michaelhays** [resend/react-email#1153]
I saw that `react-email` recently [switched](https://github.com/resend/react-email/pull/1027/files#diff-79ed911b0cab61ba07ff059e7b509532b27dbf22c33f9c6b279a9aa1315f9b5dR43) from https://github.com/yangshun/tree-node-cli to https://github.com/MrRaindrop/tree-cli to allow installation behind a corporate proxy.

`tree-cli` hasn't been updated in 4 years, and includes a lot of dangerously outdated packages (see [analysis](https://snyk.io/advisor/npm-package/tree-cli)), which is throwing some security concerns in my dependency analyzer.

It would be great if this dependency could be dropped, in favor of writing the functionality internally!

**Comment by gabrielmfern** [comment]
Great catch, thanks for opening the issue and we'll look into this.

Annoying that we have to go from library to library that is either unmaintained or breaks somewhere

**Comment by michaelhays** [comment]
Yep, super annoying. Honestly in this case, `tree-cli` is simple enough that it might make sense to refactor to be more modern, and make it an internal utility function

**Comment by gabrielmfern** [comment]
PR open! #1221

**Comment by michaelhays** [comment]
Eyy nice work! :smile:
