### ISSUE TITLE
Named export issue in react-email, when implementing in remix application! 

### ISSUE THREAD

**Issue by broisnischal** [resend/react-email#1209]
### SyntaxError: Named export 'html' not found. The requested module 'js-beautify' is a CommonJS module, which may not support all module

```ts

 💿  remix dev

 info  building...
 info  built (2.5s)
file:///home/nees/code/myresume/node_modules/@react-email/render/dist/index.mjs:49
import { html } from "js-beautify";
         ^^^^
SyntaxError: Named export 'html' not found. The requested module 'js-beautify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'js-beautify';
const { html } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at run (/home/nees/code/myresume/node_modules/@remix-run/serve/dist/cli.js:113:15)
^C
exit 130
main ~/code/myresume> 

```

### Which package is affected (leave empty if unsure)

@react-email/html

### Link to the code that reproduces this issue

https://github.com/broisnischal/myresume

### To Reproduce

install resend and send mail via the remix, 

### Expected Behavior

It should have worked without throwing the error of module!

**Comment by aboubakrbm** [comment]
Same issue with Nuxt

```
 ERROR  [worker reload] [worker init] The requested module 'js-beautify' does not provide an export named 'html'
 
  import { html } from "js-beautify";
  ^^^^
  SyntaxError: The requested module 'js-beautify' does not provide an export named 'html'
```

**Comment by gabrielmfern** [comment]
@aboubakrbm What version are you using of @react-email/render?

**Comment by aboubakrbm** [comment]
> @aboubakrbm What version are you using of @react-email/render?

This is from `pnpm-lock.yaml`:
```
/resend@3.0.0:
	(...)
	dependencies:
	    '@react-email/render': 0.0.11
```

I don't know why `@react-email/render` is a dependency for `resend` package. If I am using resend in a Nuxt project why should i deal with react-email. I think it would be better if `resend` was a independant package. 

Note: I switch to `nodemailer` and use resend smtp.

**Comment by gabrielmfern** [comment]
> I don't know why @react-email/render is a dependency for resend package. If I am using resend in a Nuxt project why should i deal with react-email. I think it would be better if resend was an independant package.

This is because Resend supports a `react` option that you can pass directly to it so that it renders it for you. Then it is an issue with the Resend SDK instead of with react-email as the latest `@react-email/render` has this fixed already.
