### ISSUE TITLE
URL is not defined during email rendering in react-email v2

### ISSUE THREAD

**Issue by matchai** [resend/react-email#1229]
### Describe the Bug

When trying to use the [`URL()` constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) in an email surfaces the error `ReferenceError: URL is not defined` in the preview.

![CleanShot 2024-01-23 at 18 54 29@2x](https://github.com/resend/react-email/assets/4658208/9132adee-2c77-4407-9c9a-6313cb12e437)

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/matchai/react-email-issue-repro/blob/url-issue-repro/emails/url-repro.tsx

### To Reproduce

Add `new URL("https://example.com")` anywhere in your email code.

### Expected Behavior

The global URL object functions as it does in other JavaScript environments.

### What's your node version? (if relevant)

21.2.0

**Comment by gabrielmfern** [comment]
PR open fixing this #1232. Thanks for opening the issue!

**Comment by pkit** [comment]
Just FYI what else is missing from an actual node env:
- perf_hooks
- http2
- setTimeout/clearTimeout
- setInterval/clearInterval
- setImmediate/clearImmediate
- URLSearchParams
- TextDecoder/TextEncoder

These are pretty common in modern modules, many more are needed for the proper nodejs builtin support.

**Comment by gabrielmfern** [comment]
Fixed and released on `react-email@2.1.1-canary.0`!
