### ISSUE TITLE
@react-email/tailwind 0.0.14 styles not working with react-email 2.0.0

### ISSUE THREAD

**Issue by seawatts** [resend/react-email#1243]
### Describe the Bug

When using react-email 2.0.0 and @react-email/tailwind 0.0.14 I am no longer seeing any styles show up. The only styles that are rendered to the page are any @media query styles. 

### Which package is affected (leave empty if unsure)

@react-email/tailwind, react-email

### Link to the code that reproduces this issue

https://github.com/resend/react-email/tree/canary/packages/tailwind

### To Reproduce

```tsx
import { Body, Head, Html, Tailwind } from '@react-email/components';

export default function Email() {
  return <Html>
    <Tailwind>
      <Head/>
      <Body className="mx-2 my-auto bg-white md:mx-auto dark:bg-slate-900 dark:text-white">
        hello
      </Body>
    </Tailwind>
  </Html>
};
```

### Expected Behavior

All Tailwind css classes to be rendered

**Comment by gabrielmfern** [comment]
For me, it seems to be working fine. 

Maybe you're expecting the classes to be kept, but the classes for usual utilities won't be kept, they'll be turned into inline styles because it has the best email client support possible here.
For media queries, though, we don't have an option.

**Comment by gabrielmfern** [comment]
I'm going to add the `Can't Reproduce` label for now until you give an actual repro I can run locally.

**Comment by seawatts** [comment]
@gabrielmfern, thanks for the prompt response and explanation of how the styles work. I will work on getting a repo up.  In the interim, here is a snippet of the output HTML in react-email. You can see here that the tailwindcss class names were not transferred to the styles attribute.

```tsx
import { Button, Container, Section } from '@react-email/components';

export default function Email() {
  return (
    <Container>
      <Section className="mb-8 mt-8 w-full text-center sm:w-1/2 md:w-1/3">
        <Button
          className="block w-2/3 rounded-md bg-[#3B8C6E] px-3 py-3 text-center text-sm font-semibold text-white shadow-sm"
          href={callbackUrl}
        >
          Sign In
        </Button>
      </Section>
    </Container>
  );
}
```

Output HTML:

```html
<table 
  align="center" 
  width="100%" 
  class="mb-8 mt-8 w-full text-center sm:w-1/2 md:w-1/3" 
  border="0" 
  cellpadding="0" 
  cellspacing="0" 
  role="presentation">
  <tbody>
    <tr>
      <td>
        <a 
          class="block w-2/3 rounded-md bg-[#3B8C6E] px-3 py-3 text-center text-sm font-semibold text-white shadow-sm" 
          href="http://localhost:3000" 
          style="line-height:100%;text-decoration:none;display:inline-block;max-width:100%;padding:0px 0px 0px 0px" target="_blank">
          <span><!--[if mso]><i style="letter-spacing: 0px;mso-font-width:-100%;mso-text-raise:0" hidden>&nbsp;</i><![endif]--></span>
          <span style="max-width:100%;display:inline-block;line-height:120%;mso-padding-alt:0px;mso-text-raise:0">Sign In</span>
          <span><!--[if mso]><i style="letter-spacing: 0px;mso-font-width:-100%" hidden>&nbsp;</i><![endif]--></span>
        </a>
      </td>
    </tr>
  </tbody>
</table>
```

Let me know if I'm missing something simple; otherwise, I'll try to get a repo up.

**Comment by seawatts** [comment]
Ah ha, I figured it out. We are trying to use `React.createContext` to share properties into sub-components. Taking that out fixes the issue. I've tried to call `useContext` as well as `<MyContext.Consumer>` but they both caused it to break.
