### ISSUE TITLE
email export not working

### ISSUE THREAD

**Issue by ababol** [resend/react-email#1245]
### Describe the Bug

After running `npx create-email@latest`

I had to install a few package to make the project working (I think there is some PR taking care of that)
```
    "react": "^18.2.0", (because not working otherwise )
    "next": "^14.1.0", (because vercel deploy is not working otherwise)
```

But I've run into another issue, when I run:

```
pnpm export
```

I am getting :
```

~/Code/shotgun/react-emails main
❯ pnpm export

> emails@0.0.18 export /Users/ababol/Code/shotgun/react-emails
> email export

✔ Preparing files...

✖ failed when rendering vercel-invite-user.js
TypeError: component.default is not a function
    at /Users/ababol/Code/shotgun/react-emails/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:778:75
    at step (/Users/ababol/Code/shotgun/react-emails/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:186:23)
    at Object.next (/Users/ababol/Code/shotgun/react-emails/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:127:20)
    at asyncGeneratorStep (/Users/ababol/Code/shotgun/react-emails/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:12:28)
    at _next (/Users/ababol/Code/shotgun/react-emails/node_modules/.pnpm/react-email@2.0.0_eslint@8.56.0/node_modules/react-email/cli/index.js:30:17)
 ELIFECYCLE  Command failed with exit code 1.
```

It correctly generate the `.js` file but you can see it's not working afer that.
My `vercel-invite-user.tsx` is the same as the one created after running `npx create-email@latest` 
=> see https://github.com/resend/react-email/blame/canary/packages/react-email/src/cli/commands/export.ts#L65 

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/resend/react-email

### To Reproduce

Just run `email export`

### Expected Behavior

Generate my template html file

### What's your node version? (if relevant)

2.0.0

**Comment by ababol** [comment]
I've fixed the issue! Let's close this 

See PR https://github.com/resend/react-email/pull/1248

**Comment by gabrielmfern** [comment]
Let's close this one once we get it merged so that others aren't confused

**Comment by nathanburgess** [comment]
Any timeline on when this fix will be available?

**Comment by gabrielmfern** [comment]
> Any timeline on when this fix will be available?

We already have it out on canary `react-email@2.1.0-canary.1`. Stable release soon.
