### ISSUE TITLE
 Error: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by steventkrawczyk** [resend/react-email#1262]
### Describe the Bug

`npx email dev` will lead to the page giving the error in title when I try it from the started project.
![Screen Shot 2024-01-28 at 1 29 55 PM](https://github.com/resend/react-email/assets/45177034/bbf85a17-aede-4656-a6c7-d7bf547d558c)

### Link to the code that reproduces this issue

Code from react-email-starter will do it

### To Reproduce

Run `npx email dev`  from the react-email-starter project

### Expected Behavior

I would expect to see preview of emails in the emails directory

**Comment by steventkrawczyk** [comment]
For future reference: Upgrade node version

**Comment by gabrielmfern** [comment]
Closing as a duplicate of #1235
