### ISSUE TITLE
Array of children gets wrapped in additional table

### ISSUE THREAD

**Issue by Hainesy** [resend/react-email#1275]
### Describe the Bug

When looping around an array to output components in JSX, an extra table is rendered wrapping the whole array.

This creates problems for me because I have additional code in a wrapping component that applies margin to children, to mimic flex gap.

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

N/A

### To Reproduce

```
<Text>Test before</Text>

// An extra table wraps the below elements
{[1, 2, 3].map(number => (
  <Text key={number}>Test {number}</Text>
))}

<Text>Test after</Text>
```

### Expected Behavior

Expected behaviour would be that the children are rendered without any additional wrapping code.

**Comment by gabrielmfern** [comment]
Couldn't reproduce from side, seems like they are rendering `p`'s just fine:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<p style="font-size:14px;line-height:24px;margin:16px 0">Test before</p>
<p style="font-size:14px;line-height:24px;margin:16px 0">Test <!-- -->1</p>
<p style="font-size:14px;line-height:24px;margin:16px 0">Test <!-- -->2</p>
<p style="font-size:14px;line-height:24px;margin:16px 0">Test <!-- -->3</p>
<p style="font-size:14px;line-height:24px;margin:16px 0">Test after</p>
```

**Comment by Hainesy** [comment]
🤦🏻‍♂️ I dug deeper, and it was down to some custom code I'd written. Very sorry to waste your time.

**Comment by gabrielmfern** [comment]
@Hainesy No worries!
