### ISSUE TITLE
Module '"@react-email/components"' has no exported member 'Markdown'

### ISSUE THREAD

**Issue by Hainesy** [resend/react-email#1276]
### Describe the Bug

It seems the components package is not exporting the markdown component, as per the docs.

**Update:** I see that as a workaround, I can install the `@react-email/markdown` package.

### Link to the code that reproduces this issue

N/A

### To Reproduce

Simply try to `import { Markdown } from '@react-email/components';`

You can see that the index.js or index.mjs files in `node_modules/@react-email/components/dist` do not include the markdown component.

### Expected Behavior

The Markdown component should be included in the package.

**Comment by paramaggarwal** [comment]
As per the docs https://github.com/resend/react-email/blob/canary/apps/docs/components/markdown.mdx#L46, this should work, hence the docs are wrong.

The code has never imported markdown yet: https://github.com/resend/react-email/blob/canary/packages/components/src/index.ts

**Comment by gabrielmfern** [comment]
Released on canary now on `@react-email/components@0.0.15-canary.2`
