### ISSUE TITLE
Markdown custom styles can't handle quotes in e.g. font property

### ISSUE THREAD

**Issue by Hainesy** [resend/react-email#1285]
### Describe the Bug

This will spit out literal quotes into the HTML, thereby ending the style attribute and producing invalid HTML and broken styles:

```<Markdown markdownCustomStyles={{ h1: { font: "700 23px / 32px \"Roobert PRO\", system-ui, sans-serif" }}}># Hello</Markdown>```

Producing

<img width="449" alt="image" src="https://github.com/resend/react-email/assets/520883/bac7b939-9462-40c7-b4c7-429c2cb11c12">

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

See above

### To Reproduce

See above

### Expected Behavior

Quotes should be escaped/replaced.

**Comment by Surinderpro** [comment]
1. Identify the affected package version and update it to the latest version, as this issue may have been addressed in newer releases.

2. If updating the package doesn't resolve the issue, consider the following workaround:

   - Manually escape quotes:Escape the quotes inside the font property to ensure they are not treated as literal quotes in the HTML.

 ` <Markdown markdownCustomStyles={{ h1: { font: "700 23px / 32px &quot;Roobert PRO&quot;, system-ui, sans-serif" }}}># Hello</Markdown>`

 - Alternative syntax:Use single quotes for the font property to avoid conflicts with double quotes in the HTML.

   ` <Markdown markdownCustomStyles={{ h1: { font: '700 23px / 32px "Roobert PRO", system-ui, sans-serif' }}}># Hello</Markdown>`

**Comment by gabrielmfern** [comment]
Reopening until we get the fix released at least on canary.

**Comment by gabrielmfern** [comment]
Fix released under `@react-email/markdown@0.0.9` or `@react-email/components@0.0.16`!
