### ISSUE TITLE
bringing back the refs

### ISSUE THREAD

**Issue by advancedtw** [resend/react-email#1287]
### Goals

1. framer motion requires component to have a ref 

### Background

during the pr #948 all refs have been removed without any mention of why that happened.  I'm using framer motion and building a simple visual email designer for my own need. I would like to animate some styles changes like text color etc.

### Proposal

possible solution would look something like that
```tsx
type ButtonProps = React.AnchorHTMLAttributes<HTMLAnchorElement>;

const Button = forwardRef<HTMLAnchorElement, ButtonProps>(
  ({ children, style, target = "_blank", ...props }, forwardedRef) => {
    return (
      // ...
      <a ref={forwardedRef} {...props}>
        <span style={buttonTextStyle(pb)}>{children}</span>
      </a>
      // ...
    );
  },
);
```

_Originally posted by @advancedtw in https://github.com/resend/react-email/discussions/1286_

**Comment by gabrielmfern** [comment]
Closing in favor of the discussion #1286
