### ISSUE TITLE
Cannot start react-email Server 

### ISSUE THREAD

**Issue by louremipsum** [resend/react-email#1302]
### Describe the Bug

After freshly installing `npx create-email@latest` I followed the steps from [docs](https://react.email/docs/getting-started/automatic-setup) of react-email and when I typed `npm run dev` in the terminal then it gave an error. I even tried the [manual setup](https://react.email/docs/getting-started/manual-setup) and it didn't work. Someone, please help, I don't know if I missed something. I am installing using the command in a completely fresh folder. 

## Terminal Picture
![image](https://github.com/resend/react-email/assets/72456774/03e10717-5571-4944-8120-30a5ea1c881f)

* As indicated in the project, it is trying to find the Next server and app/pages dir which exists in Next and nowhere is it written in the docs that for this to work there should be Next.js installed.
* I even did the same in the Next.js project directory and it wasn't able to find the app/pages directory even when I specified the directory with the `--dir` flag in the dev command.
* Also for some reason, even when the server starts and it starts serving on a port then it displays my Next.js website when I don't even have it serving on localhost at that time and I'm not able to figure it out on how to get the react-email server start running.

# **UPDATE**
I uploaded the code to a repository for this issue and when I cloned it in a fresh folder and ran `npm i` and `npm run dev` it gave me a new error :(
![image](https://github.com/resend/react-email/assets/72456774/1ee807b7-b947-478e-b942-8beef843e2c9)
![image](https://github.com/resend/react-email/assets/72456774/22cec6dd-2e82-4e6e-ab57-cfc6e418d1ce)
![image](https://github.com/resend/react-email/assets/72456774/dab1953b-df32-4bd8-81f4-dc0e89c89c70)

## VSCode Specs
Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

## Package.json
```json
{
  "name": "emails",
  "version": "0.0.18",
  "private": true,
  "workspaces": [
    ".react-email"
  ],
  "scripts": {
    "build": "email build",
    "dev": "email dev",
    "export": "email export"
  },
  "dependencies": {
    "@react-email/components": "0.0.14",
    "react-email": "2.0.0"
  }
}
```

## Brower 
Google Chrome
Version 121.0.6167.161 (Official Build) (64-bit)

## OS and Device
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎05-‎10-‎2022
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/louremipsum/react-email-starter

### To Reproduce

```bash
npx create-email@latest
npm install
npm run dev
```
Type these commands

### Expected Behavior

The expected Behaviour is that a `.react-email` folder should be made the react-email server should start and by default the emails tsx files should be served at http://localhost:3000 as shown in the docs,

### What's your node version? (if relevant)

18.18.0

**Comment by louremipsum** [comment]
Thank you for the quick reply Gabriel :), I will update to the canary version and will tell you the details

**Comment by louremipsum** [comment]
Thank you, Gabriel
 `react-email@2.1.0-canary.1` works :) and the server is starting all right, although the image path is not resolved correctly so they are not visible

**Comment by gabrielmfern** [comment]
> although the image path is not resolved correctly so they are not visible

Where are you placing static files? Also, did you modify the default emails directory? Might be related to #1265

**Comment by louremipsum** [comment]
![image](https://github.com/resend/react-email/assets/72456774/a16a0fb8-05cc-4677-8754-a0eab116216b)
this is my current workspace structure

**Comment by gabrielmfern** [comment]
Try moving your `static` directory into `emails/static`

**Comment by FatahChan** [comment]
I had the same issue, installing the canary version and moving the `static` dir to `emails/static` did resolve the issue.

I am noticing a performance issue, this is my first time using react email, so I am unsure if this is a windows specific or just how it is.

Basically I switch between emails it takes at least 1 second to switch, the vercel-invite-user email took at least 3s

I am more than happy to file bug, if it's actually a bug

https://github.com/resend/react-email/assets/30260221/d22c968d-3f83-4fee-800c-bf884906ff66

**Comment by gabrielmfern** [comment]
Hey @FatahChan 

> I am more than happy to file bug, if it's actually a bug

Not a bug, so no need to file a bug. 
But it is something that bothers me, I wish we did have better performance on that. Would be nice to brainstorm
a few ideas on how to tackle this though. Maybe a discussion?

I do know that initial render takes a bit longer because we don't really build the NextJS preview server
so it always re-compiles the preview page which really is not optimal, but not sure if would make a very large
difference.

**Comment by gabrielmfern** [comment]
Closing this as stale and also, seems like the canary at the time fixed it.
