### ISSUE TITLE
NodeJS CommonJS

### ISSUE THREAD

**Issue by lokacoding** [resend/react-email#1316]
### Describe the Bug

I dont get this package running using normal nodejs syntax.

I checked out the demo project where I want to first only console.log the rendered html.

**package.json**
```
{
  "name": "emails",
  "version": "0.0.18",
  "private": true,
  "type":"module",
  "workspaces": [
    ".react-email"
  ],
  "scripts": {
    "build": "email build",
    "dev": "email dev",
    "export": "email export"
  },
  "dependencies": {
    "@react-email/components": "0.0.14",
    "nodemailer": "^6.9.9",
    "react-email": "2.0.0"
  }
}
```

**app.js:**
```
import { render } from '@react-email/render'
import { StripeWelcomeEmail } from './emails/stripe-welcome'

const emailHtml = render(StripeWelcomeEmail());
console.log(emailHtml);
```

**./emails/stripe-welcome.js:**
```
import { Body, Button, Container, Head, Hr, Html, Img, Link, Preview, Section, Text } from "@react-email/components";
import * as React from "react";

const baseUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : "";

export const StripeWelcomeEmail = () => (
  <Html>
    <Head />
    ...
      </Html>
);
export default StripeWelcomeEmail;
```

tried running node app.js command but getting error:

node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(

If I change import to:

```
import { StripeWelcomeEmail } from './emails/stripe-welcome.js'
```

I'm getting following error, but everything is installed as package!
```
(base) marius@MBP-M react-email-starter % node app.js
file:///Users/marius/Downloads/React_Projekte/react-email/react-email-starter/emails/stripe-welcome.js:9
  <Html>
  ^

SyntaxError: Unexpected token '<'
```

### Link to the code that reproduces this issue

in code above.

### To Reproduce

it's in the description.

### Expected Behavior

it's in the description.

### What's your node version? (if relevant)

18.18.2

**Comment by gabrielmfern** [comment]
This error means you are importing the JSX without first compiling. JSX doesn't run directly inside of javascript, so you would need a compilation step or use something like bun.

**Comment by gabrielmfern** [comment]
To be clear though, what I said above doesn't mean you can't still preview your emails inside of `email dev`'s server, it will because of the way we build your email before actually rendering it.
