### ISSUE TITLE
email dev, directory links broken.

### ISSUE THREAD

**Issue by TioGeorge91** [resend/react-email#1354]
### Describe the Bug

Using email dev with custom --dir 
When opening preview all root tsx.jsx, etc files are ok and can be navigated but any files located inside folders have the wrong link. 
They get absolute path instead of relative. 
![image](https://github.com/resend/react-email/assets/93913663/5ab89bec-ec7a-465f-81d5-051bc6529acb)

### Link to the code that reproduces this issue

none

### To Reproduce

npm script: 
email dev --dir="./example"

create a folder and add a react file in a subfolderinside  (eg ./example/test/File.tsx) 

try to navigate to that with the links on the left when running preview server.

### Expected Behavior

Being able to navigate to the correct path (assuming it should be relative , but links point to absolute path)

**Comment by gabrielmfern** [comment]
This might also be OS related, if you don't mind me asking, what OS was this happening on?

**Comment by gabrielmfern** [comment]
Was able to reproduce the issue now. Also I saw that it's Windows anyways because of the absolute path in your screenshot.
I'll take a look into fixing this ASAP.

**Comment by gabrielmfern** [comment]
A workaround for now: Instead of running like `email dev -d src/emails` you can do `email dev -d src\emails` and it should work AFAIK.

**Comment by gabrielmfern** [comment]
Fixed and released under `react-email@2.1.1-canary.1`!

See https://github.com/resend/react-email/releases/tag/react-email%402.1.1-canary.1 for more info.
