### ISSUE TITLE
[TailwindCSS]: Weird import behavior

### ISSUE THREAD

**Issue by gfffrtt** [resend/react-email#1367]
### Describe the Bug

I am working on this project and when trying to import the `<Tailwind />` component from `@react-email/components`, it says that it doesn't exist, even after installing all modules, re installing, cleaning the whole repo for the service, and yet, still can't seem to import it.

![image](https://github.com/resend/react-email/assets/153773731/49f6ff73-19c0-4892-a5c9-2ceb0fe287c5)

### Which package is affected (leave empty if unsure)

@react-email/components, @react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/gfffrtt/bank

### To Reproduce

Clone repository and remove the `// @ts-expect-error` from the file locate in `services/mail/src/mail/templates/sign_in.tsx`.

### Expected Behavior

Not have to add an comment to expect a unknown import error.

### What's your node version? (if relevant)

I am using bun

**Comment by gabrielmfern** [comment]
Tried reproducing but just couldn't. Could this be because of your version of bun here — i.e. something that has been fixed on the latest?

Going to close this as not planned for now as I couldn't reproduce.
