### ISSUE TITLE
react icons not rendering

### ISSUE THREAD

**Issue by AhmedRyad22** [resend/react-email#1368]
### Describe the Bug

while in dev you can use react icons, but when i use nodemailer + react email render ,  there will be no icons, in Gmail at least where i recieve the mail.

### Link to the code that reproduces this issue

/

### To Reproduce

use react icons in email

### Expected Behavior

working in render as in dev

### What's your node version? (if relevant)

18

**Comment by illiyyin** [comment]
I think it's because react-icons compiled the icon into svg, email doesn't support svg render. Try use png icon

**Comment by gabrielmfern** [comment]
@illiyyin Is exactly right on this. @AhmedRyad22 Please refer to https://www.caniemail.com/features/image-svg/ for support, SVGs are not well-supported on Gmail.

Closing this as it's not really an issue of ours, but an issue with @AhmedRyad22's template.
