### ISSUE TITLE
ESLint couldn't determine the plugin "turbo" uniquely.

### ISSUE THREAD

**Issue by mattinannt** [resend/react-email#1402]
### Describe the Bug

In my Next.js project I'm also using the `eslint-config-turbo` package and when using a different version from the one used in react-email I'm getting this error while linting:
```
ESLint couldn't determine the plugin "turbo" uniquely.
```

### Link to the code that reproduces this issue

-

### To Reproduce

Install react-email into a turborepo repository where a different version of `eslint-config-turbo` is used and try linting.

### Expected Behavior

Dev tools of react-email doesn't effect other repositories where react-email is used

### What's your node version? (if relevant)

20.10.0

**Comment by gabrielmfern** [comment]
This has since been fixed since [`react-email@3.0.0`](https://resend.com/blog/react-email-3)
