### ISSUE TITLE
Using Resend in production

### ISSUE THREAD

**Issue by AliReza1083** [resend/react-email#1421]
### Describe the Bug

I am trying to send email through API router in Next.js.

It is working fine in localhost but not in production.
I am also using ngrok, it is working fine there but not in the real production.

This is the error I get:

<img width="639" alt="image" src="https://github.com/resend/react-email/assets/99729607/79a38b19-45dc-4133-a42b-74b3b517a9d3">

### Link to the code that reproduces this issue

https://github.com/AliReza1083/Portfolio/blob/main/app/api/comment-email/route.ts

### To Reproduce

I don't know how to reproduce the bug but you can use API route and send email but try it on production.

### Expected Behavior

I expect it to send email in production.

### What's your node version? (if relevant)

Latest

**Comment by AliReza1083** [comment]
I had to use the latest version of @react-email/component

**Comment by gabrielmfern** [comment]
His issue was that it was timing out due to using the older, slower version of `@react-email/tailwind`.
