### ISSUE TITLE
Live refresh not working for components

### ISSUE THREAD

**Issue by quentez** [resend/react-email#1433]
### Describe the Bug

The watch system to live refresh the web UI when something changes works for the email templates themselves, but not the components they depend on, even when they're in a `_components` subfolder.

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

n/a

### To Reproduce

1. Create a `_components` subfolder.
2. Create a `header.tsx` re-usable component.
3. Use that component in an email template.
4. Modify that component.

### Expected Behavior

The web preview UI should automatically pick up the new changes. Instead, a manual refresh is needed.

**Comment by neilpoulin** [comment]
I just installed react-email on a new project today, and am having the same issue. I am running React Email v2.1.4 on Node 18.16.0. 

Making changes directly to my email template file show the changes quickly & automatically, but changes in any _imported component_ do not trigger HRM or a reload. 

Note: the only way to get my changes inside of imported components (shared header/footer, etc), is to refresh the browser window. Switching between different templates and back does _not_ show the updated component.

**Comment by gabrielmfern** [comment]
@neilpoulin What is the file structure that still has the issue?

**Comment by kno-raziel** [comment]
It works for me using the following structure:

 ```
react-email-starter/
┣ emails/
┃ ┣ _components/
┃ ┃ ┣ Content.tsx
┃ ┃ ┣ Footer.tsx
┃ ┃ ┣ Header.tsx
┃ ┃ ┣ Heading.tsx
┃ ┃ ┣ HtmlBase.tsx
┃ ┃ ┗ Main.tsx
┃ ┣ static/
┃ ┃ ┣ notion-logo.png
┃ ┃ ┣ plaid-logo.png
┃ ┃ ┣ plaid.png
┃ ┃ ┣ stripe-logo.png
┃ ┃ ┣ vercel-arrow.png
┃ ┃ ┣ vercel-logo.png
┃ ┃ ┣ vercel-team.png
┃ ┃ ┗ vercel-user.png
┃ ┣ notion-magic-link.tsx
┃ ┣ plaid-verify-identity.tsx
┃ ┣ stripe-welcome.tsx
┃ ┗ vercel-invite-user.tsx
┣ node_modules/
┣ package-lock.json
┣ package.json
┗ readme.md
```

**Comment by gabrielmfern** [comment]
@kno-raziel Did it not work on some other file structure? Would love it if you could share it as well

**Comment by kno-raziel** [comment]
@gabrielmfern  similar structure as the one above but components folder was at same level as email folder, any change in the components didn't trigger the live reload.

**Comment by gabrielmfern** [comment]
@kno-raziel Thinking here that is another issue separate from this one, the issue might only happen when it is outside the emails directory. Could you open one issue for that? Would greatly appreciate it, and I'll start taking a look into it right now as well.

**Comment by gabrielmfern** [comment]
@kno-raziel Yup, confirmed, just looked a bit through our code and indeed this was a missing edge case that we needed to implement. The watcher of files we had was not looking for changes into files outside of your emails' directory, now it looks precisely into the ones that were introduced into the internal dependency graph to avoid this issue.

Will most likely open a PR for this tomorrow.
