### ISSUE TITLE
Does not work with Next 14.2.2

### ISSUE THREAD

**Issue by rogueturnip** [resend/react-email#1435]
### Describe the Bug

The Next 14.2.2 requires React 18.3.0 while react-send is on the 18.2.x version.  Unable to update to the newer versions of Next because of this.

As React 19 was released (beta) and Next will likely update to support it's more important for react-email to increase the supported React version.

### Link to the code that reproduces this issue

no code link

### To Reproduce

With existing setup on Next 13 and react-email try to update to Next 14

### Expected Behavior

Should update without module conflict.

**Comment by jessicarush** [comment]
I created a new project project with Next 14.2.3 which installed `react@18.3.1`. I forced the install of @react-email/component with:

```bash
npm install @react-email/components --legacy-peer-deps
```

I have two email templates in my app and have tested them, so far all appears to be working fine. This is obviously not a solution, just adding my +1 to the issue.

**Comment by praveentcom** [comment]
+1

**Comment by Catevika** [comment]
+1

**Comment by arashn0uri** [comment]
+1

**Comment by davidaragundy** [comment]
+1

**Comment by gabrielmfern** [comment]
This has been fixed on the latest for our packages. To get it, you will need to upgrade all of the packages you have installed from us. See https://github.com/resend/react-email/issues/1432#issuecomment-2083443578 for more info.
