### ISSUE TITLE
Could not resolve "react/jsx-runtime"

### ISSUE THREAD

**Issue by restocked** [resend/react-email#1442]
### Describe the Bug

Following the automatic setup this error is being thrown.

### Which package is affected (leave empty if unsure)

@react-email/components, create-email, react-email

### To Reproduce

Just run the automatic process, step by step.

npx create-email@latest
<img width="1040" alt="Screenshot 2024-04-30 at 15 52 24" src="https://github.com/resend/react-email/assets/48245948/73117b57-650a-4aab-b649-01e67cbbf95c">

### Expected Behavior

To compile and show emails template

### What's your node version? (if relevant)

20.12.2 or 18.17.1

Using macOS Ventura 14.4.1

**Comment by gabrielmfern** [comment]
Did you find this was an issue on your side? Or the cause of it exactly?

**Comment by restocked** [comment]
> Did you find this was an issue on your side? Or the cause of it exactly?

I fixed by doing this https://github.com/resend/react-email/issues/1422#issuecomment-2072163519
