### ISSUE TITLE
Tailwind media queries causing exception

### ISSUE THREAD

**Issue by WillsB3** [resend/react-email#1449]
### Describe the Bug

Given this code:

```tsx
import {
  Body,
  Button,
  Head,
  Html,
  Preview,
  Tailwind,
} from "@react-email/components";
import * as React from "react";

export const TailwindError = () => (
  <Html>
    <Head />
    <Preview>Log in with this magic link</Preview>
    <Body>
      <Tailwind
        config={{
          theme: {
            extend: {
              colors: {
                brand: "#007291",
              },
            },
          },
        }}
      >
        <Button
          href="https://example.com"
          className="bg-brand px-3 py-2 font-medium leading-4 text-white md:w-[32px]"
        >
          Click me
        </Button>
      </Tailwind>
    </Body>
  </Html>
);

export default TailwindError;

```

The following error occurs:

![Screenshot 2024-05-08 at 22 50 04](https://github.com/resend/react-email/assets/868834/76bde6bc-1034-4e51-bec6-2b29f75727d8)

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

See above

### To Reproduce

1. Run `npx create-email@latest`
2. Replace contents of one of the sample templates with the code above
3. Preview the template in the development server
4. Observe the error

### Expected Behavior

The media query classes work without error

### What's your node version? (if relevant)

v18.19.0

**Comment by gabrielmfern** [comment]
You need to have the Tailwind component above the Head. The error message says it, it just isn't very well formatted there 😅.

So, change it to the following and it should work.

```patch
 import {
   Body,
   Button,
   Head,
   Html,
   Preview,
   Tailwind,
 } from "@react-email/components";
 import * as React from "react";
 
 export const TailwindError = () => (
+   <Tailwind
+     config={{
+       theme: {
+         extend: {
+           colors: {
+             brand: "#007291",
+           },
+         },
+       },
+     }}
+   >
   <Html>
     <Head />
     <Preview>Log in with this magic link</Preview>
     <Body>
-      <Tailwind
-        config={{
-          theme: {
-            extend: {
-              colors: {
-                brand: "#007291",
-              },
-            },
-          },
-        }}
       >
         <Button
           href="https://example.com"
           className="bg-brand px-3 py-2 font-medium leading-4 text-white md:w-[32px]"
         >
           Click me
         </Button>
-      </Tailwind>
     </Body>
   </Html>
+ </Tailwind>
 );
 
 export default TailwindError;
```

**Comment by WillsB3** [comment]
🤦 Sorry, I misread the error message and thought it was ok as long as the template had a `<Head>` 😅 .

I can open a PR to update the docs to try and make this more clear if that's helpful.

**Comment by gabrielmfern** [comment]
@WillsB3 For sure, if you might also be interested in updating our component with the error message to use something like a `<pre>` it would also be great!

**Comment by Zain-ul-din** [comment]
@gabrielmfern tailwind class is there but i think code gen is not working any idea on how to fix it?

![image](https://github.com/user-attachments/assets/45e199c9-3d29-42c2-9374-0aeab59a96f8)

**Comment by Zain-ul-din** [comment]
sorry, it's generating in HTML I don't why it's not showing in the console.

![image](https://github.com/user-attachments/assets/ec19cb48-e1de-4445-8d45-5bff3c9a14e9)

**Comment by Zain-ul-din** [comment]
sorry, it's generating in HTML I don't why it's not showing in the console.

![image](https://github.com/user-attachments/assets/ec19cb48-e1de-4445-8d45-5bff3c9a14e9)

**Comment by astonfuture** [comment]
With the latest `react-email/components` version 0.0.26, using media queries causes an [Object object] exception in the head

```
Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
```
