### ISSUE TITLE
incorrect next dependencies for react email? 

### ISSUE THREAD

**Issue by davidhu2000** [resend/react-email#1464]
### Describe the Bug

I received a security alert

> Next.js Server-Side Request Forgery in Server Actions #69

that mentioned affected nextjs version are `>= 13.4.0, < 14.1.1`, which confused me since I was using 14.1.4

```
yarn why -R next
└─ web@workspace:.
   ├─ react-email@npm:2.1.1 (via npm:2.1.1)
   │  └─ next@npm:14.1.0 [9aa8f] (via npm:14.1.0 [9aa8f])
   └─ next@npm:14.1.4 [0ef78] (via npm:14.1.4 [0ef78])
```

i realized that react-email is bringing in another version of next. 

I wonder if `next` should be a peerDependency instead? otherwise anyone installed it either be stuck with the next version that matches react-email, or have a duplicate copy like me. 

There are also a few more in the same vein, such as `react`, `react-dom`

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/resend/react-email/blob/481f4d20aad8e6f3bac5e73d8f5dabcf20d7f640/packages/react-email/package.json#L57

### To Reproduce

1. create next app using a version that isn't 14.1.0
2. `yarn add react-email@2.1.1`
3. `yarn why -R next`

### Expected Behavior

react email should not bring it's own copy of nextjs.

**Comment by gabrielmfern** [comment]
We actually do use Next for the preview server, that's why it's warning there for you. But we've updated to the latest Next on our latest canary so try `react-email@2.1.3-canary.1` and it shouldn't warn you anymore.
