### ISSUE TITLE
"Error: [render-resolver] "onLoad" filter is not a valid Go regex" when loading mail in preview app

### ISSUE THREAD

**Issue by chrishoermann** [resend/react-email#1479]
### Describe the Bug

I used `npx create-email@latest` to init a repo but when I start I get the following error message:

![grafik](https://github.com/resend/react-email/assets/53531653/a5ac2ce0-5574-4eb8-97cb-ffa5bdb7c199)

Any Ideas what this error means or where it originates?

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

`npx create-email@latest` and run dev

### To Reproduce

I used `npx create-email@latest` and started the server. I also tired the manual setup, but it didn't work either.

I run this on a windows machine with win 11 and  pnpm `9.1.0` if this is relevant.

### Expected Behavior

Should display the selected email in the preview app without any errors

### What's your node version? (if relevant)

20.3.1

**Comment by clauddr** [comment]
Hi Chris, one way of solving this is to install the latest version of react-email. You can do a
 `npm install react-email@2.1.3-canary.1 `
,this is the latest version and has next updated. It solved the issue for me, hope it does the same.

**Comment by chrishoermann** [comment]
@clauddr Hi Claus, thanks this also solved the problem for me. cheers
