### ISSUE TITLE
Text in heading is converted to all caps when exporting emails as plainText

### ISSUE THREAD

**Issue by andrewerrico** [resend/react-email#1493]
### Describe the Bug

When exporting emails as `plainText` all text inside the Heading components are all converted to all caps

### Which package is affected (leave empty if unsure)

@react-email/heading

### Link to the code that reproduces this issue

n/a

### To Reproduce

```tsx
import {
  Container,
  Heading,
  Html,
  Section,
  Text,
} from '@react-email/components'

export default function TestEmail() {
  return (
    <Html>
      <Section>
        <Container>
          <Heading as='h1'>This is an H1</Heading>
          <Heading as='h2'>This is an H2</Heading>
          <Heading as='h3'>This is an H3</Heading>
          <Heading as='h4'>This is an H4</Heading>
          <Heading as='h5'>This is an H5</Heading>
          <Heading as='h6'>This is an H6</Heading>
        </Container>
        <Container>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt
            voluptate temporibus nam doloribus vitae sequi? Praesentium
            consequuntur officiis eaque iure, repudiandae consectetur obcaecati
            expedita, quos itaque earum minima quidem? Quos?
          </Text>
        </Container>
      </Section>
    </Html>
  )
}

```

Exporting this email as `plainText` results in this:

```
THIS IS AN H1


THIS IS AN H2


THIS IS AN H3

THIS IS AN H4

THIS IS AN H5

THIS IS AN H6

Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt voluptate
temporibus nam doloribus vitae sequi? Praesentium consequuntur officiis eaque
iure, repudiandae consectetur obcaecati expedita, quos itaque earum minima
quidem? Quos?
```

### Expected Behavior

```txt
This is an H1

This is an H2

This is an H3

This is an H4

This is an H5

This is an H6

Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt voluptate
temporibus nam doloribus vitae sequi? Praesentium consequuntur officiis eaque
iure, repudiandae consectetur obcaecati expedita, quos itaque earum minima
quidem? Quos?
```

**Comment by gabrielmfern** [comment]
This is configurable through the `htmlToTextOptions` property in the rendering options. Here's the original selectors from `html-to-text` that make this behavior:

https://github.com/html-to-text/node-html-to-text/blob/5b7ca1c1a736a730c9a4fa1b6db6172e50f4ee3e/packages/html-to-text/src/html-to-text.js#L66-L73

You can override with selectors, like:

```js
render(<h1>Testing heading to see if it gets uppercased</h1>, {
  plainText: true,
  htmlToTextOptions: {
    selectors: [
      { selector: 'h1', format: 'heading', options: { leadingLineBreaks: 3, trailingLineBreaks: 2, uppercase: false } },
    ],
  },
})
```

You would also need to add the selectors for the other headings as well, though.

**Comment by andrewerrico** [comment]
> This is configurable through the `htmlToTextOptions` property in the rendering options. Here's the original selectors from `html-to-text` that make this behavior:
> 
> https://github.com/html-to-text/node-html-to-text/blob/5b7ca1c1a736a730c9a4fa1b6db6172e50f4ee3e/packages/html-to-text/src/html-to-text.js#L63-L76
> 
> You can override with selectors, like:
> 
> ```js
> render(<h1>Testing heading to see if it gets uppercased</h1>, {
>   plainText: true,
>   htmlToTextOptions: {
>     selectors: [
>       { selector: 'h1', format: 'heading', options: { leadingLineBreaks: 3, trailingLineBreaks: 2, uppercase: false } },
>     ],
>   },
> })
> ```
> 
> You would also need to add the selectors for the other headings as well, though.

Is this available through `cli`? I can't find it in the docs anywhere

**Comment by gabrielmfern** [comment]
@andrewerrico I don't think it is actually, but adding this might be a bit too much to do through flags. Wonder what would you prefer on this?

**Comment by andrewerrico** [comment]
> @andrewerrico I don't think it is actually, but adding this might be a bit too much to do through flags. Wonder what would you prefer on this?

Our team's currently working on a backend re-write. 
We have a nx monorepo with react apps and some custom libraries. I just added react-emails to a library and they are being built and copied to a separate backend repo with `yarn email export`, then we use handlebars to inject data into the templates.

Maybe we'll have to look into a node script to handle this instead of using `export`

**Comment by gabrielmfern** [comment]
> Maybe we'll have to look into a node script to handle this instead of using export

I would recommend you do so, yeah, since you are using handlebars you might face a few other issues that you would need a separate script for too.
