### ISSUE TITLE
Error: Build failed

### ISSUE THREAD

**Issue by leog** [resend/react-email#1497]
### Describe the Bug

Getting errors when previewing out-of-the-box emails.

```
Error: Build failed with 3 errors: emails/notion-magic-link.tsx:11:7: ERROR: Could not resolve "@react-email/components" emails/notion-magic-link.tsx:26:4: ERROR: Could not resolve "react/jsx-runtime" emails/notion-magic-link.tsx:152:38: ERROR: [plugin: render-resolver] Failed trying to import `renderAsync` from either `@react-email/render` or `@react-email/components` to be able to render your email template. Maybe you don't have either of them installed?
```

<kbd>
<img src="https://github.com/resend/react-email/assets/467258/be2a6048-9924-44ef-96c2-776caeca7a42" />
</kbd>

### Which package is affected (leave empty if unsure)

create-email

### Link to the code that reproduces this issue

-

### To Reproduce

Follow the instructions here https://react.email/docs/getting-started/automatic-setup

### Expected Behavior

Have out-of-the-box emails preview successfully as shown in docs.

### What's your node version? (if relevant)

v18.18.2

**Comment by gabrielmfern** [comment]
Thinking this might be because by [yarn modern's pnp](https://yarnpkg.com/features/pnp). Here's an issue someone else also had https://github.com/resend/react-email/issues/1422#issuecomment-2072310780

**Comment by iantanwx** [comment]
@gabrielmfern getting the same issue, there are no pnp files in my project.

**Comment by iantanwx** [comment]
following up, I had to install react and react-dom to my package. the project is a `pnpm` monorepo.

**Comment by leog** [comment]
Not sure what's happening but I have this error in a personal project, works in one computer and not in another.

Also using pnpm workspaces, code in https://github.com/propsto/props.to/tree/auth-domain and by running in the root `pnpm i` and then `pnpm dev:email` you should be able to reproduce the issue... or not. Tried node v20 and v18.

Also tried including `react` and `react-dom`.

**Comment by gabrielmfern** [comment]
@iantanwx From the comment I mentioned, the yarn files were not on their project but rather on their home:

> That was it! I didn't use pnp (never actually have so I'm not sure where it came from), but I had .pnp.cjs .pnp.loader.mjs in my home directory.

From what you mention @leog, 

> works in one computer and not in another

I am pretty sure this is the same problem as the comment mentions. Also, the repo you mention doesn't have the script nor does it have react-email installed 😅.

**Comment by leog** [comment]
@gabrielmfern notice I shared a repo with a particular branch `auth-domain`, in it there is a package under packages folder called `email`

**Comment by gabrielmfern** [comment]
I see it now, but no issues on my side:

![image](https://github.com/resend/react-email/assets/88866334/216f60e6-3d69-44d4-9607-32841453d222)

Here's a separate comment on an issue talking about this https://github.com/evanw/esbuild/issues/2647#issuecomment-1516574767. Thinking you have ran `yarn` on the home directory, or at some higher up directory, which causes esbuild to find it up all the way there and expect the modules' resolution to be done by it, not by pnpm.

**Comment by leog** [comment]
Can't wait to go back to my other computer and find those bastard files braking my emal dev flow 😄 
Thanks for the pointer @gabrielmfern, I'll let you know later today.

**Comment by leog** [comment]
yeahp, found it at `/Users/username//.pnp.cjs`, fixed! thanks all!
