### ISSUE TITLE
Documentation on main site missing `@react-email/components` from install

### ISSUE THREAD

**Issue by j-mcgregor** [resend/react-email#1501]
### Describe the Bug

Title sums it up but you're missing the `@react-email/components` from the install line and the very next step requires it but it won't be installed.

<img width="829" alt="image" src="https://github.com/resend/react-email/assets/22773767/b142253f-a2bc-4a04-b786-5bcef41e1af7">

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

https://react.email/docs/integrations/postmark

### To Reproduce

Literally follow the steps on the guide -> https://react.email/docs/integrations/postmark

### Expected Behavior

Step 2 shouldn't show any errors as everything will be installed

### What's your node version? (if relevant)

20

**Comment by gabrielmfern** [comment]
Thanks for pointing this out, seems like the other guides for integration also have this issue.

**Comment by 7H3XXX** [comment]
Hello, since the changes suggested by @j-mcgregor are not already made, can I make a PR that solves it ?

**Comment by gabrielmfern** [comment]
@7H3XXX Certainly feel free to do it.

**Comment by 7H3XXX** [comment]
@gabrielmfern I also noticed a missing dependency in the plunk integration (```@react-email/render```), I went ahead and added it.

**Comment by gabrielmfern** [comment]
This was fixed by #1509 and should be correct now
