### ISSUE TITLE
The link element is not navigating the user to the appropriate href specified.

### ISSUE THREAD

**Issue by abuzain432432** [resend/react-email#1507]
### Describe the Bug

I have specified the links in the footer, but I don't know why they are not working. This is the code. I am testing it in the Gmail client.

### Which package is affected (leave empty if unsure)

@react-email/link

### Link to the code that reproduces this issue

https://github.com/abuzain432432/React-Email-Bug-In-Link_Component

### To Reproduce

1. **Set up a project with React Email**:

   - Initialize a new project using React or Next.js.
   - Install the `react-email` package.

2. **Create an email template**:

3. **Copy code from the linked repo to your project**:

### Expected Behavior

Clicking on social media links in the footer of the email should
redirect to the specified URLs. For example, a Facebook link should
take the user to a specific Facebook profile page, not to an unrelated
or random URL.

### What's your node version? (if relevant)

20

**Comment by gabrielmfern** [comment]
What happens when you click the URL? Does it redirect the user successfully, or does it not work at all?

My understanding here is that email clients, like Gmail, will generate some safe URL of theirs that redirects into your URL. Is that what you don't expect here? Because, beyond that, it seems to work fine.

**Comment by abuzain432432** [comment]
When I click on the link it redirects me to a broken URL. I don't know why. in the actual case, it should redirect me to this URL https://twitter.com/MuuveGroup
in Gmail client
![image](https://github.com/resend/react-email/assets/101734048/f24bdfb9-a557-47d9-91cc-64b3983bcbeb)
in development preview
![image](https://github.com/resend/react-email/assets/101734048/ce3eec1c-d9e4-4204-a8ac-9ba380f4c2ce)

**Comment by gabrielmfern** [comment]
Does it not work when you actually open the URL either?

**Comment by abuzain432432** [comment]
No, I am not using Resend I am using SandGrid, and answer to your first question "No, I am getting this"
![image](https://github.com/resend/react-email/assets/101734048/17058791-a62e-4c55-9dc1-ef4472ebad88)

**Comment by gabrielmfern** [comment]
Could this be related to [SendGrid's click tracking](https://www.twilio.com/docs/sendgrid/ui/account-and-settings/tracking#click-tracking)?

**Comment by gabrielmfern** [comment]
Closing as stale.
