### ISSUE TITLE
Tailwind breaks padding on `Section`

### ISSUE THREAD

**Issue by bernaferrari** [resend/react-email#1519]
### Describe the Bug

I made a simple demo using `NextJS` instead of react-email and enabled TailwindCSS.

If `cellPadding` weren't hardcoded (or the `...props` came after it), allowing the user to modify it would work (not sure it has compatibility issues). Else, seems like Tailwind somehow is resetting it? The weird part is that no matter what I do, it stays ignored.

https://github.com/resend/react-email/assets/351125/c43b29b4-c041-4a21-be1a-1c496f18de56

### Which package is affected (leave empty if unsure)

@react-email/section

### Link to the code that reproduces this issue

https://github.com/user-attachments/files/16023070/demo.zip

**Comment by gabrielmfern** [comment]
Though it is worth investigating if we really need to force `cellPadding` to 0, the problem in your case is that Tailwind's `@tailwind base` adds in a `border-collapse: collapse;` to tables which causes the behavior you mention about the table ignoring the padding. So, all you need to do is remove the `@tailwind base` from the CSS file, or rather just use an iframe for the email template as we do on the preview server:

https://github.com/resend/react-email/blob/8a41d4430b50eeb99ed0c79a96860bcd877c5538/packages/react-email/src/app/preview/%5B...slug%5D/preview.tsx#L93-L99

Closing this as not planned.
