### ISSUE TITLE
Wrong usage of ComponentPropsWithoutRef should be ComponentPropsWithRef

### ISSUE THREAD

**Issue by sunshineo** [resend/react-email#1521]
### Describe the Bug

For example `<Text>` component, when I try `<Text ref={textRef}>` I got
```
Type '{ children: string; ref: MutableRefObject<any>; }' is not assignable to type 'IntrinsicAttributes & Readonly<Pick<DetailedHTMLProps<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "key" | keyof HTMLAttributes<...>>>'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & Readonly<Pick<DetailedHTMLProps<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "key" | keyof HTMLAttributes<...>>>'.ts(2322)
```

### Which package is affected (leave empty if unsure)

@react-email/text

### Link to the code that reproduces this issue

https://github.com/resend/react-email/blob/canary/packages/text/src/text.tsx

### To Reproduce

<Text ref={textRef}>

### Expected Behavior

The ref should be passed down

**Comment by gabrielmfern** [comment]
I don't think that's because of the wrong type, it's just because we haven't released a version of forward refs yet, so the `React.forwardRef`, as is on the canary branch, should allow you to pass in the `ref`.

**Comment by sunshineo** [comment]
Thank you @gabrielmfern . I did not notice that by default it shows the "canary" branch. I thought it's the code I have locally.
