### ISSUE TITLE
CLI email export - undefined properties

### ISSUE THREAD

**Issue by Orlandohub** [resend/react-email#1534]
### Describe the Bug

When the email template requires props to render the content and running the CLI command `email export` it throws the following error: 
```
TypeError: Cannot read properties of undefined (reading <prop>)
```
I've defined the necessary `PreviewProps` which work fine when running the `email dev` command

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://gist.github.com/Orlandohub/a4d738fff7109615de1432dec0b8698f

### To Reproduce

1. Create a template which requires props, specifically an object with nested fields
2. access the object nested fields inside the template function
3. run `email export` CLI command

### Expected Behavior

Would expect the export to output the HTML file without the undefined properties error

### What's your node version? (if relevant)

20.13.1

**Comment by gabrielmfern** [comment]
`email export` is not for preview, thus it doesn't use `PreviewProps`. `email export` is meant for users who use separate templating, so the outputted HTML is meant for actual use, not preview.
If you want props to be used in the `email export`, you could set these props as default values, like the following:

```jsx
function MyComponent({
  myProp = 'the default value'
}) {
  // ...
}
```

In other words, `email export` is meant for use cases that are not the best case scenario. The best case scenario is rendering the email templates dynamically at the point of sending the email. Such as in this example: 

https://github.com/resend/react-email/blob/4409b0108a95aba11aaab038ac3d3e61bb067c6e/examples/nodemailer/src/index.tsx#L15-L24

This provides a much better developer experience than templating manually, so lookout for that. The places where you would need this templating separate from React would generally be:
* If you are sending the email template through another language
* If you are being forced to do templating by some email platform you are using

Closing this as not planned as it isn't an issue.
