### ISSUE TITLE
Ref still not accessible

### ISSUE THREAD

**Issue by john093e** [resend/react-email#1535]
### Describe the Bug

I noticed in the following commits that ref was added to some components:
[chore: Add forward ref to all relevant components](https://github.com/resend/react-email/commit/e61bf3d517cc6ee0efd3a03854a6c20cd288977e)
[fix(preview, text): Improper use of forward ref](https://github.com/resend/react-email/commit/f5cf05c26235bcdd4633446f35ccd769019c3c29)

However, it seems the components still do not accept a ref prop as expected.

I tried with the following package versions:
0.0.21
0.0.21-canary.0

Thanks in advance for your help

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

-

### To Reproduce

Add ref to any components that should accept it ( button, section, text, ...).

e.g:
```tsx
export const HrComponent = ({ className }: HrProps) => {
  const {
    connectors: { connect, drag },
  } = useNode()

  return (
    <Hr
      ref={(ref) => {
        if (ref) {
          connect(drag(ref))
        }
      }}
      className={className}
    />
  )
}
```

in VSCode : 
Cannot assign type '{ ref: (ref: any) => void; className: string | undefined; }' to type 'IntrinsicAttributes & Readonly<Omit<DetailedHTMLProps<HTMLAttributes<HTMLHRElement>, HTMLHRElement>, "ref">>'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & Readonly<Omit<DetailedHTMLProps<HTMLAttributes<HTMLHRElement>, HTMLHRElement>, "ref">>'.ts(2322)

### Expected Behavior

Add ref to a react-email/component should be allowed

**Comment by gabrielmfern** [comment]
Sorry for this being confusing, that canary you tested on (0.0.21-canary.0) was meant for testing #1474, but in retrospect was a mistake as it gets confusing and the versioning of packages become a mess. One more thing is that we hadn't yet released the version that includes the addition of forward ref. I purposefully kept them out when doing other releases to publish later on, which I just did.

You can use it through `@react-email/components@0.0.22-canary.0`. Let me know if you find any issues with it and I'll fix them. Thanks for the patience.

**Comment by john093e** [comment]
Thank you so much for the release, sorry i didn't realised it wasn't.

Note: found a typo : import type { PrismLangauge } from "@react-email/components"
PrismLangauge <- PrismLanguage
