### ISSUE TITLE
Component Row doesnt work properly 

### ISSUE THREAD

**Issue by yan-pi** [resend/react-email#1557]
### Describe the Bug

the columns work fine, but the row component doesn't work, and I can't use a div (with flexbox) because it also doesn't work well. I think it has something to do with [this issue](https://github.com/resend/react-email/issues/889) too.

![image](https://github.com/user-attachments/assets/bbaf834b-764c-40ab-b2a8-443f38acdeed)

### Which package is affected (leave empty if unsure)

@react-email/row, react-email

### Link to the code that reproduces this issue

cant provide, its a private company project :/

### To Reproduce

Use the Row component inside a Column. I'm also using Tailwind.

### Expected Behavior

Work as `<div className="flex flex-row">`

### What's your node version? (if relevant)

20.13.1

**Comment by gabrielmfern** [comment]
What do you mean with “the Row doesn't work” exactly?

Also, React Email does not do any crazy magical transformation to make flex box or other email HTML unsupported features to work. React Email provides you with the components that will behave as you expect until its limits. But flex box is not included in that. This means that you still need to worry about what kinds of styles you end up using, and if they have good support or not.

**Comment by nnmhuy** [comment]
It seems that the Row component is rendering a new table instead of <tr>

**Comment by gabrielmfern** [comment]
@nnmhuy That's expected behavior, we do use an internal `<table>` for the `Row` component.

**Comment by gabrielmfern** [comment]
Closing this as stale. Properly explain the problem and I'll reopen.
