### ISSUE TITLE
 Tailwind component in React-email doesn't respect base styles

### ISSUE THREAD

**Issue by FranciscoMoretti** [resend/react-email#1615]
## Issue Description

When using the Tailwind component in React-email, it doesn't respect Tailwind base styles. This results in unwanted "default" styles, such as underlined links.

## Proposed Solution

Linking the Tailwind pre-flight to normalize styles is necessary and can be done with the `<Head>` component:

```jsx
<Html>
  <Head>
    {/* Tailwind pre-flight to reset styles */}
    <link href="https://unpkg.com/tailwindcss@^2/dist/base.min.css" rel="stylesheet"/>
  </Head>
  <Preview>{previewText}</Preview>
  <Tailwind>
    {/* ... */}
  </Tailwind>
</Html>
```

## Related Issue

This solution introduces another issue, as mentioned in [#1519](https://github.com/resend/react-email/issues/1519).

`@tailwind base` adds `border-collapse: collapse;` which causes tables to ignore padding.

## Question

A potential solution might be to use `border-collapse: separate` in components with a table tag.

Is this the right approach to solve both issues?

### Link to the code that reproduces this issue

https://github.com/FranciscoMoretti/react-email-tailwind

### To Reproduce

Remove `<link href="https://unpkg.com/tailwindcss@^2/dist/base.min.css" rel="stylesheet"/>` from the `Head`.

### Expected Behavior

Expect the Tailwind component to include tailwind base styles.

**Comment by gabrielmfern** [comment]
I think we can't recommend that users do what you are trying to, the preflight is not 100% necessary and it breaks things. It also would be quite hard to implement internally as `<link>` does not have good support, and the `<style>` is better but still not best.

But I wouldn't worry so much about that, as you can create a component wrapping the `<Link>` and define the styles you always want there. Also, the benefit of working on an email template, as opposed to a complete website, is that you can see the complete email template and notice issues more easily.

**Comment by FranciscoMoretti** [comment]
Thanks for explaining that. I was wondering why this wasn't suggested by the library docs. Closing the issue
