### ISSUE TITLE
Hot refresh not working in 3.0.0

### ISSUE THREAD

**Issue by elliotnash** [resend/react-email#1623]
### Describe the Bug

Hot refresh seems to not work in >=3.0.0, from a project created directly from the template. There are no console logs indicated a watched file has changed either, as there were in <3.0.0.

### Which package is affected (leave empty if unsure)

@react-email/preview

### Link to the code that reproduces this issue

https://github.com/elliotnash/react-email-hot-refresh

### To Reproduce

1. Create a new react-email project with `npx create-email@latest` (or clone the provided repo)
2. Run `npm i`
3. Run `npm dev`
4. Open an email component and edit some text

### Expected Behavior

On save, the new content should hot reload into the email preview.

### What's your node version? (if relevant)

Npm: 10.8.1 - Node: v20.16.0

**Comment by gabrielmfern** [comment]
That's crazy this got through our testing, thanks for letting us know!

Fixing it right now.

**Comment by gabrielmfern** [comment]
Fixed on [`react-email@3.0.1`](https://github.com/resend/react-email/releases/tag/react-email%403.0.1)!

**Comment by elliotnash** [comment]
That was fast! Thanks
