### ISSUE TITLE
yarn build is broken in react-email@3.0.1

### ISSUE THREAD

**Issue by semtselishev** [resend/react-email#1631]
### Describe the Bug

When I follow the official doc setup
1. yarn create email
2. yarn install
3. yarn build

I'm getting an error like this
```
$ email build
   ⠦ Installing dependencies on `.react-email`Error: Unable to install the dependencies and it exited with code: 1
    at ChildProcess.<anonymous> (<path>/react-email-starter/node_modules/react-email/dist/cli/index.js:2556:44)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```
{
  "name": "react-email-starter",
  "version": "0.0.32",
  "private": true,
  "scripts": {
    "build": "email build",
    "dev": "email dev",
    "export": "email export"
  },
  "dependencies": {
    "@react-email/components": "0.0.23",
    "react-email": "3.0.1",
    "react-dom": "18.3.1",
    "react": "18.3.1"
  },
  "devDependencies": {
    "@types/react": "18.3.4",
    "@types/react-dom": "18.3.0"
  }
}
```

### Link to the code that reproduces this issue

the default code from the official documentation

### To Reproduce

1. yarn create email
2. yarn install
3. yarn build

### Expected Behavior

the build should be working

### What's your node version? (if relevant)

v20.12.2

**Comment by gabrielmfern** [comment]
This worked on my side, not sure what is going on here but I can't reproduce.

**Comment by semtselishev** [comment]
Hi @gabrielmfern , 
is there some way to get debug logs from this command to see the dependencies that failed to resolve?

**Comment by taylor-lindores-reeves** [comment]
My .react-email package never builds. My package.json I have:

`"email:dev": "email dev --dir src/app/services/resend/templates -p 8080"`

This works, but when I view the preview it shows the following for all templates:
![Screenshot 2024-08-28 at 18 33 16](https://github.com/user-attachments/assets/93ed04eb-8df2-4901-90e1-8fd2570c3e27)

**Comment by taylor-lindores-reeves** [comment]
> My .react-email package never builds. My package.json I have:
> 
> `"email:dev": "email dev --dir src/app/services/resend/templates -p 8080"`
> 
> This works, but when I view the preview it shows the following for all templates: ![Screenshot 2024-08-28 at 18 33 16](https://private-user-images.githubusercontent.com/27443324/362392887-93ed04eb-8df2-4901-90e1-8fd2570c3e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjcxNzMsIm5iZiI6MTcyNDg2Njg3MywicGF0aCI6Ii8yNzQ0MzMyNC8zNjIzOTI4ODctOTNlZDA0ZWItOGRmMi00OTAxLTkwZTEtOGZkMjU3MGMzZTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE3NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZTY1M2MyYmE5NjFiODc5YjI5M2UxZGU1NDUxYmIxZjZhZmFjNmI0MmNiZjUyZWU2MjIxYTU2YzcwMTgwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f2YbGW1z_QnWEaBdMOFvOeNpmTi0ldZ7LZws_4436Gw)

Ignore me, I was importing a file which imported the Request object, so my fault there!

**Comment by gabrielmfern** [comment]
@taylor-lindores-reeves If the Request you are trying to use is the Node class, and it doesn't work we will take that as a bug.
Anything that works in Node, should run fine in the preview server, including globals and even node modules.

**Comment by gabrielmfern** [comment]
Closing as not planned because of inactivity. If anyone experiences this, let me know and I'll reopen.
