### ISSUE TITLE
 Named export 'html' not found.

### ISSUE THREAD

**Issue by solidoracle** [resend/react-email#1664]
### Describe the Bug

Open nextauth routing in my nextjs project, and when I build I get this error
<img width="1257" alt="Screenshot 2024-09-06 at 16 19 24" src="https://github.com/user-attachments/assets/e20e6863-43e2-4746-82d0-30afda649271">

### Link to the code that reproduces this issue

N/a

### To Reproduce

N/a

### Expected Behavior

N/a

**Comment by gabrielmfern** [comment]
Provide a proper reproduction, and also make sure that you are using the latest `@react-email/render` as the module is being imported differently and that could have already fixed your issue.

Closing as not planned until you provide a proper reproduction.
