### ISSUE TITLE
react-email-starter/node_modules breaks all my project

### ISSUE THREAD

**Issue by GuysmoB** [resend/react-email#1665]
### Describe the Bug

Hi,

I followed the automatic setup guide but once i do `npm i` inside `react-email-starter` folder, all components of my projects are broken. I have this kind of error for each one :
![image](https://github.com/user-attachments/assets/3b143790-bfa1-43d1-bfb5-ee889c9c802f)

Then if i run `npm build` on the root, the error is related to `react-email-starter/node_modules/@types/react/ts5.0/index").ReactNode'.`

![image](https://github.com/user-attachments/assets/68968e93-457f-4639-9ff2-9d6a73de54c9)

Any idea ?
Thank you !

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

no repo

### To Reproduce

NextJs project version 14.2.5,
```
npx create-email@latest
cd react-email-starter
npm i

```

### Expected Behavior

I must build the project without error but the problem seems to be related to my config i guess.

tsconfig.json
```
{
	"compilerOptions": {
		"target": "es5",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"incremental": true,
		"checkJs": true,
		"jsx": "preserve",
		"useUnknownInCatchVariables": false,
		"types": ["react/experimental"],
		"paths": {
			"@/*": ["./*"]
		},
		"plugins": [
			{
				"name": "next"
			}
		]
	},
	"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "jest.config.js"],
	"exclude": ["node_modules"]
}
```

react-email-starter package.json

```
{
  "name": "react-email-starter",
  "version": "0.0.34",
  "private": true,
  "scripts": {
    "build": "email build",
    "dev": "email dev",
    "export": "email export"
  },
  "dependencies": {
    "@react-email/components": "0.0.25",
    "react-email": "3.0.1",
    "react-dom": "18.3.1",
    "react": "18.3.1"
  },
  "devDependencies": {
    "@types/react": "18.3.4",
    "@types/react-dom": "18.3.0"
  }
}
```

**Comment by gabrielmfern** [comment]
Seems to me like this is because of `@types/react` from `react-email-starter` not matching the one in your project, what you can do is use the same version for both. Or, you can also just remove the `package.json` in `react-email-starter` and move the necessary dependencies into your main project, since you don't really *need* to have a separate `package.json`.
