### ISSUE TITLE
Preview component causes email send to fail - with mailSend only 

### ISSUE THREAD

**Issue by AyoCodess** [resend/react-email#1683]
### Describe the Bug

if we add:  **Preview Component**

```js
  <Tailwind>
				  <Head />
				 <Preview>
					Heading text
				  </Preview> 
				  <Body className="bg-white font-sans">
					  <{...}
				 </Section>
```
      
 we get this error: 
```
      
      'Error sending email with mailSend:' {
  headers: {
    'cache-control': 'no-cache, private',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8c3f1b8fbdd782aa-IAD',
    connection: 'close',
    'content-type': 'application/json',
    date: 'Mon, 16 Sep 2024 07:22:50 GMT',
    server: 'cloudflare',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    'transfer-encoding': 'chunked',
    'x-apiquota-remaining': '985',
    'x-apiquota-reset': '2024-09-17T00:00:00Z',
    'x-ratelimit-limit': '120',
    'x-ratelimit-remaining': '119'
  },
  body: {
    message: 'The html field contains invalid input.',
    errors: { html: [Array] }
  },
  statusCode: 422
}
```

when we remove this component the email sends successfully.

the emails ends successfully with **resend** with the preview component in the email

### Which package is affected (leave empty if unsure)

@react-email/preview

### Link to the code that reproduces this issue

using latest resend package

### To Reproduce

create a email and add preview component using mail send as the agent 

### Expected Behavior

should not get an error

### What's your node version? (if relevant)

20

**Comment by gabrielmfern** [comment]
What if you move the `<Preview>` to inside the `<Body>`?

**Comment by AyoCodess** [comment]
> What if you move the `<Preview>` to inside the `<Body>`?

This solved the issue. thank you

**Comment by Hainesy** [comment]
@gabrielmfern I have discovered that if the preview contains more than 52 characters, then the email arrives completely blank.

Moving it inside `<Body>` seems to fix the issue, however all the examples I looked at had the preview outside the body.

It would be helpful to update documentation to be clear on this.

**Comment by Hainesy** [comment]
Actually, I've just run into this issue again where it's breaking even when the `Preview` component is inside the body, again only when the text is more than 52 chars long. It seems this issue is not resolved, can we reopen this ticket?

**Comment by gabrielmfern** [comment]
@Hainesy I think that issue is separate to this one, could you open one for that? Also, what email client is having it arrive blank?

**Comment by fafifox** [comment]
Had the same issue, it's happening when `Preview` content has more than 53 chars

**Comment by fafifox** [comment]
@gabrielmfern In my case emails were not even sent: `The html field contains invalid input`, (i'm using nodemailer to send)

**Comment by gabrielmfern** [comment]
@fafifox How did the rendered HTML look like then? I also find it weird that the error happens with more than 53 characters when the maximum preview length is 150. 🤔
