### ISSUE TITLE
Jest tests detect dynamic imports on render@1.0.1

### ISSUE THREAD

**Issue by NathanDiegues** [resend/react-email#1703]
### Describe the Bug

NestJS application.

**Packages:**
 "@nestjs/cli": "^10.3.2",
"@react-email/components": "0.0.25",
"react": "^18.3.1",
"react-dom": "^18.3.1",
"react-email": "3.0.1",

**Error:**
```
LeadExistsCreationAttemptTemplate › should render the button correctly

    TypeError: A dynamic import callback was invoked without --experimental-vm-modules

      29 |     return {
      30 |       subject: template.subject(props),
    > 31 |       html: await render(template.mailComponent(props)),
         |                         ^
      32 |     };
      33 |   }
      34 | }

      at ../../../node_modules/.pnpm/@react-email+render@1.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@react-email/render/dist/node/index.js:132:39
      at ../../../node_modules/.pnpm/@react-email+render@1.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@react-email/render/dist/node/index.js:60:61
      at __async (../../../node_modules/.pnpm/@react-email+render@1.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@react-email/render/dist/node/index.js:44:10)
      at render (../../../node_modules/.pnpm/@react-email+render@1.0.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@react-email/render/dist/node/index.js:130:36)
      at TemplateService.renderEmail (email/domain/services/template.service.ts:31:25)
```

Hello, I'm upgrading the react-emails package version on a project. It's currently working fine with the new async render and I'm able to render and send the emails properly. However the tests aren't working and jest is accusing the render function of having a dynamic import callback.
This did not happen on the previous package version.

### Which package is affected (leave empty if unsure)

@react-email/render

### Link to the code that reproduces this issue

https://github.com/resend/react-email/blob/canary/packages/render/src/node/index.ts

### To Reproduce

1. Create a file that returns a React.JSX.Element
2. Create a function that renders said React.Element
3. Create a jest spec file that tests said function.
4. Running this test should fail with the error message above.

Example of test:
```

  describe('renderEmail', () => {
    it('should render the email subject and html', async () => {
      const payload = {
        email: faker.internet.email(),
        date: new Date(),
      };

      const { html, subject }: MailRender = await service.renderEmail(payload);

      expect(subject).toContain('Log in');
      expect(html).toContain('Log In');
      expect(html).toContain(
        `You will be logged in as <b>${payload.email}</b>`,
      );
    });
  });
});
```

### Expected Behavior

The test should be ran normally and no error message should be shown.

### What's your node version? (if relevant)

v22.6.0

**Comment by gabrielmfern** [comment]
The thing causing the error was previously implemented on `renderAsync`, but as you are now using the code that does the dynamic import it now causes the issue. This is not a problem with React Email per se, its just something about Jest's support for dynamic imports. I would recommend you do what the docs say you do, that is passing the experimental vm option to Node.

> Execute node with --experimental-vm-modules, e.g. node --experimental-vm-modules node_modules/jest/bin/jest.js or 
> NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" npx jest etc.
>
> On Windows, you can use [cross-env](https://github.com/kentcdodds/cross-env) to be able to set environment variables.
>
> If you use Yarn, you can use yarn node --experimental-vm-modules $(yarn bin jest). This command will also work if you use [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp).
>
> If your codebase includes ESM imports from *.wasm files, you do not need to pass --experimental-wasm-modules to node. Current implementation of WebAssembly imports in Jest relies on experimental VM modules, however, this may change in the future.

See https://jestjs.io/docs/next/ecmascript-modules for more info.

**Comment by jacknewberry** [comment]
I have also encountered this issue using react-email with node and jest.

It sounds like you are saying that react-email with node needs the `--experimental-vm-modules` flag.

If this is the case, maybe consider updating your docs to mention this requirement.

**Comment by jacknewberry** [comment]
Running jest with `node --experimental-vm-modules` makes my tests twice as slow, and almost doubles their heap size.

It seems I can work around this by adding `@react-email/render@0.0.17` and using that rather than the render exported from @react-email/components

This appears to work with `@react-email/components@0.0.25` and `react-email@3.0.1`.

**Comment by DeepaPrasanna** [comment]
As @jacknewberry mentioned, I had to downgrade from  `@react-email/render@1.0.4` to `@react-email/render@0.0.17` to make this work.

**Comment by fmsouza** [comment]
I've fixed that by changing my import method.

Before I had something like:
```typescript
async function sendEmail() {
  return render(
    <MyEmail {...props} />
  );
}
```

And then I've changed for:
```typescript
async function sendEmail() {
  const { MyEmail } = await import('./path/to/my-email');
  return render(
    MyEmail({ ...props })
  );
}
```
