### ISSUE TITLE
Background Issues

### ISSUE THREAD

**Issue by ArifAA14** [resend/react-email#1717]
### Describe the Bug

Hey everyone,

I'm a little lost honestly, 

So when I browse to react-email docs > examples and send any of the several examples (lets say the Vercel-Invite User for this case)  to my email, and then I open the email lets say in my iOS Email App, it renders just as expected with the background colour as well.

But when I setup a new project using react-email and copy and paste the same template from the docs example to my project and send, I'm unable to get the background colour? 

Screenshot examples below -

Email sent through react-email docs > examples 
![IMG_2017](https://github.com/user-attachments/assets/4d0cb2a3-6621-42fd-a2da-afdf54cde5dc)

Email sent through my local react-email installation (same vercel template copied from the docs > examples)
![IMG_2018](https://github.com/user-attachments/assets/d07363b3-2a27-4418-a1f9-ac832ed121be)

### Link to the code that reproduces this issue

n/a

### To Reproduce

Simply follow the automatic installation guide provided in the docs - 

`npx create-email@latest`

### Expected Behavior

The background colour appears on the emails sent through react-email docs > examples 

but on a local installation of an automatic setup, it doesn't

**Comment by gabrielmfern** [comment]
Why did you close this one @ArifAA14? Did you end up fixing it?

**Comment by ArifAA14** [comment]
Hey @gabrielmfern sorry for the extremely late response as I had given up entirely!

Recently dove back into react-email and faced the same issue immediately. 

However, this time I have a solution, I think.

```
   <Head>
        <style>{":root {color-scheme: light;}"}</style> // Apple Mail won't force its background regardless of what mode you are using 
      </Head>
```

Just adding this works.
