### ISSUE TITLE
@react-email/components breaks with React 19 + @types/react@18.3.5

### ISSUE THREAD

**Issue by luskin** [resend/react-email#1743]
### Describe the Bug

After updating React 19, @types/react and nextjs to stable 15.0.0 @react-email/components is breaking our application. The error is on every component exported from the package with a version of: `0.0.26-canary.4`

```
'Section' cannot be used as a JSX component.

Its type 'ForwardRefExoticComponent<Readonly<Omit<DetailedHTMLProps<TableHTMLAttributes<HTMLTableElement>, HTMLTableElement>, "ref">> & RefAttributes<HTMLTableElement>>' is not a valid JSX element type.
```

We are on latest `@react-email/components` canary @ `0.0.26-canary.4`

### Link to the code that reproduces this issue

https://github.com/resend/react-email/blob/canary/packages/section/src/section.tsx#L5

### To Reproduce

Upgrade to latest React + types

### Expected Behavior

`forwardRef` should be removed for canary release as canary.

### What's your node version? (if relevant)

22

**Comment by imprakharshukla** [comment]
Also happens with the Html component

**Comment by gabrielmfern** [comment]
Can you share a reproduction for the error?

**Comment by darthmaim** [comment]
You should use `@types/react@npm:types-react@19.0.0-rc.1` instead of `@types/react@18.3.5` when using react 19, maybe this already resolves your issue.

**Comment by gabrielmfern** [comment]
@luskin We are using the types for React 19 internally and there aren't any of the issues you mention. So that we can be sure, I'll repeat, can you share a reproduction of the error?

**Comment by elie222** [comment]
Simple temporary fix is to do `as any` btw

**Comment by gabrielmfern** [comment]
@elie222 Seems as that is another error, not the same one as on the original comment for the issue

**Comment by elie222** [comment]
> @elie222 Seems as that is another error, not the same one as on the original comment for the issue

I fixed it in my case by updating React types for Resend package in my monorepo.

**Comment by gabrielmfern** [comment]
Closing this as stale, if anyone experiences this, please share a reproduction and I'll reopen.

**Comment by gabrielmfern** [comment]
@MarioPon11 That seems about right on what could be the cause for it. I'd not recommend you downgrade the types since you're using React 19 anyways. What I'd recommend is you have a single `@types/react` on the monorepo's dependencies instead, and then you don't have to sync them all.

**Comment by AlejandroYanes** [comment]
I recently did the migration to react 19 and next 15 and had this error with radix-ui components, [I found this update fixed it](https://github.com/lucide-icons/lucide/issues/2488#issuecomment-2383082404), basically, you need to update the `path` in your `tsconfig.json` and add this:

```json
"paths": {
  "react": ["./node_modules/@types/react"]
}
```

Specially if you have a monorepo, you need to make sure all your packages & apps are on the same version of React
