### ISSUE TITLE
Improve deployment flow

### ISSUE THREAD

**Issue by zenorocha** [resend/react-email#407]
Currently, if you want to deploy your React Email app into Vercel, you need to go to the `.react-email` folder and run the `vercel --prod` command from there.

Ideally, users should be able to run the `vercel` command from the root folder or connect their GitHub repos.

@m-shaka do you want give it a try?

**Comment by m-shaka** [comment]
Me? 😅 
Sorry, but actually I have no motivation for deploying React Email app 🙏

**Comment by zenorocha** [comment]
hehe you never know ;)

**Comment by caiodomingues** [comment]
@zenorocha If you change the root directory of the project to `.react-email` it works normally :)

**Comment by andrerfneves** [comment]
Deploying with Vercel doesn't seem to work for me. I run into weird dependency issues. Is this how the demo for react-email site is deployed? Would love to understand the best way to deploy this to Vercel.

**Comment by gabrielmfern** [comment]
This should be fixed as of `react-email@2.0.0`.

Check the [changelog](https://react.email/docs/changelog#jan-19-2024) and our [blog post](https://resend.com/blog/react-email-2) for more info on this.
