### ISSUE TITLE
Package manager is not being detected correctly

### ISSUE THREAD

**Issue by vighnesh153** [resend/react-email#411]
I have a starter setup of `react-email` which I did by following the [documentation here](https://react.email/docs/getting-started/automatic-setup)

When I run the `dev` or `export` npm scripts, I get `yarn` command not found error.

```sh
> email dev

✔ Emails preview generated
⠋ Installing dependencies...
✔ Dependencies installed
/bin/sh: yarn: command not found
```

Upon investigation, I think the `detect-package-manager` doesn't seem to be working as desired. 

[Snippet from the dev command](https://github.com/resendlabs/react-email/blob/71f548657e4f8ee522aa5c3f449d2cf74d277904/packages/react-email/source/commands/dev.ts#L39-L44)

I see that in the `catch` block, we are not logging the error. We could do 2 things:

* Log the error so that it would be helpful to debug the issue (Maybe we can cut a ticket to the `detect-package-manager` repo?)
* We can default to `npm` instead of `yarn` because everyone will have `npm` installed as it comes bundled with `node` but not everyone has `yarn`.

**Comment by DinoZoidDev** [comment]
I'm currently getting this issue, please resolve this ASAP!

**Comment by Jaarson** [comment]
Just installed react-mail for the first time and exactly the same issue: `/bin/sh: yarn: command not found`

**Comment by bukinoshita** [comment]
> Hey guys! Nice tool you have here! I'm trying to setup a local environment and I still get this issue (it then freeze) :
> 
> ```shell
> > npm run dev
> 
> > emails@0.0.0 dev
> > email dev
> 
> ✔ Emails preview generated
> ⠋ Installing dependencies...
> ✔ Dependencies installed
> /bin/sh: 1: yarn: not found
> ```
> 
> I'm using NPM
> 
> ```
> {
>   emails: '0.0.0',
>   npm: '9.3.1',
>   node: '18.14.0',
>   v8: '10.2.154.23-node.22',
>   uv: '1.44.2',
>   zlib: '1.2.13',
>   brotli: '1.0.9',
>   ares: '1.18.1',
>   modules: '108',
>   nghttp2: '1.51.0',
>   napi: '8',
>   llhttp: '6.0.10',
>   uvwasi: '0.0.14',
>   acorn: '8.8.1',
>   simdutf: '3.1.0',
>   undici: '5.14.0',
>   openssl: '3.0.7+quic',
>   cldr: '42.0',
>   icu: '72.1',
>   tz: '2022g',
>   unicode: '15.0',
>   ngtcp2: '0.8.1',
>   nghttp3: '0.7.0'
> }
> ```
> 
> I've followed this documentation : https://react.email/docs/getting-started/automatic-setup
> 
> ```
> npx create-email@latest
> cd react-email-starter
> npm install
> npm run dev
> ```
> 
> Is there a fix, or am I doing something wrong? Cheers

Looks like the fix is not working. Let's re-open.

**Comment by igas** [comment]
Internally detection is done through lock files. @Grraahaam and others, can you please do `ls -a`?

**Comment by gabrielmfern** [comment]
This should not happen the same as of `react-email@2.0.0` and should now be fixed.

Check the [changelog](https://react.email/docs/changelog#jan-19-2024) and our [blog post](https://resend.com/blog/react-email-2) for more info on this.
