### ISSUE TITLE
[BUG] respect html entities

### ISSUE THREAD

**Issue by haxxxton** [resend/react-email#441]
When performing a `email export`, the output file appears to replace htmlentities with their rendered equivalent rather than leave them as htmlentities.

Steps to reproduce:
- add `&nbsp;` or `&rsquo;` to a template
- run `email export`
- rendered output contains ` ` and `’` rather than htmlentity

**Comment by gabrielmfern** [comment]
Seems like react-dom itself is the one who replaces the html entities like that. Maybe the JSX transform, actually?

If you wrap your entities like:

```jsx
<>{'&nbsp;'}</>
```

The entities will be kept the same, as long as you don't have `--pretty`.

**Comment by gabrielmfern** [comment]
TypeScript itself does that upon compilation, and then React DOM is the one that replaces other selective characters with their respective HTML entities back again, but a white space is not one of these characters
