### ISSUE TITLE
Button component custom styles are duplicated on the tree

### ISSUE THREAD

**Issue by praveentcom** [resend/react-email#505]
Path: /components/button

The styles applied on the button are duplicated. Upon checking the rendered code, it looks like the style applied is written on both the <a> and <span> tags.

Notice the border radius of 8px getting rendered weird due to this.

<img width="822" alt="Rendered Button" src="https://user-images.githubusercontent.com/82172535/221355396-b18b301f-78f0-4f38-8946-ac53fb06cb32.png">

<img width="520" alt="Rendered Code" src="https://user-images.githubusercontent.com/82172535/221355425-49851989-1761-42de-b247-60007058c065.png">

**Comment by bukinoshita** [comment]
A few of the duplicated styles are needed for Outlook, but this is definitely a bug where the border is also duplicated. Thanks for reporting.
