### ISSUE TITLE
dev - Folders "clickable'

### ISSUE THREAD

**Issue by Bugs5382** [resend/react-email#521]
#447  created a situation where folders are clickable in the UI and it spits out an error. Plus the icon needs to be different. I am already working on this code. Folders should be at the top of the listing.

**Comment by EmersonGarrido** [comment]
@Bugs5382  
Has this problem not been resolved already?

**Comment by adrian-patt** [comment]
Not solved, still having this issue in 1.9.0 and up. Folders show as files and cause errors when clicked.

**Comment by gabrielmfern** [comment]
This has since been solved with `react-email@2.0.0` since we have added complete support for folders on the preview server.

See https://resend.com/blog/react-email-2
