### ISSUE TITLE
The last link doesn't get active on the documentation page

### ISSUE THREAD

**Issue by NiazMorshed2007** [resend/react-email#610]
### Describe the Bug

On the documentation page, the last link on the right side isn't active even after clicking the link. Looks like it only gets active if the scrollbar reaches the top of that section.

![Recording 2023-03-29 175435](https://user-images.githubusercontent.com/77217706/228530049-3bcca795-7096-4bcc-8453-42b4e43a4a63.gif)
gets

### Link to the code that reproduces this issue

https://react.email/docs/introduction

### To Reproduce

Click the "authors" link on the right side and notice it doesn't get active.

### Expected Behavior

Should be active

**Comment by gabrielmfern** [comment]
Is this Mintlify's default behavior or is this our fault?

**Comment by NiazMorshed2007** [comment]
seems it's the default behaviour,, nvm, closing this issue 👍
