### ISSUE TITLE
Missing UI Feedback after Successful Email Sent can Lead to Double Sending

### ISSUE THREAD

**Issue by lordelogos** [resend/react-email#714]
### Describe the Bug

I have identified an issue in the application where there is a lack of user interface (UI) feedback after a successful email is sent. This can potentially lead to users unintentionally sending multiple emails due to the absence of a clear indication of success.

### Which package is affected (leave empty if unsure)

client, demo

### Link to the code that reproduces this issue

It can be reproduced on the demo website (https://demo.react.email/preview/vercel-invite-user)

### To Reproduce

- Visit the [demo website](https://demo.react.email/preview/vercel-invite-user) and choose any template
- Press the `send` button in the top right
- Input your email in the `RECIPIENT` field
- Press the `Send` button

There is no feedback in the UI on send success and it lead me to send a couple of times before I checked my mail box.

### Expected Behavior

After successfully sending an email, the application should provide some form of UI feedback to reassure the user that the email was sent and to prevent unintended double-sending.

I have developed a solution for this issue (can be seen below). Upon successful email sending, I have implemented a notification that appears in the UI to inform the user about the successful delivery of the email. This will help prevent the user from accidentally sending multiple emails.

![react-email-success-toast-demo](https://github.com/resendlabs/react-email/assets/67395687/3ff82087-94e8-484c-b1ac-becf83fe6189)

**Comment by gabrielmfern** [comment]
Closing this as completed since we have implemented a nice toast since 2.0.0 of the CLI.
