### ISSUE TITLE
Error 404 in development server when using Nextjs 12

### ISSUE THREAD

**Issue by fernandes77** [resend/react-email#722]
## Problem

We use react-email in a Nextjs 12 project and aren't ready to upgrade to 13 yet. When running the development server with `email dev`, we get a Nextjs 404 page:

![image](https://github.com/resendlabs/react-email/assets/48812482/5a24ae8c-ad0a-4375-9f02-972d56607887)

## Reason

`.react-email` uses the `app` directory which is not supported by Nextjs 12.

## Workaround

A workaround we found for this is to use Nextjs 13 inside the `.react-email` folder by manually changing the `package.json` file. We then reinstall the packages and run `next dev` inside `.react-email`.

## Possible solutions

1. Since the `.react-email` folder uses the `app` directory, the Nextjs version for it should be 13 no matter what version the project uses.
2. Support older versions by using the pages directory (more work than .1).

### Link to the code that reproduces this issue

https://github.com/fernandes77/react-email-with-next-12

### To Reproduce

To reproduce, install dependencies and run `pnpm email` in the project above.

### Expected Behavior

Nextjs 12 will be installed and an `app` directory will be created, causing localhost:4000 to display a 404 page.

**Comment by nicolassanmar** [comment]
I had the same issue when using Next 12.
I solved it by locally patching `react-email` with `pnpm` by hardcoding a set version for `next` of `13.4.6` here:
https://github.com/resendlabs/react-email/blob/main/packages/react-email/source/utils/sync-package.ts#L11-L14

What should we do? `react-email` does not require `next` so, hardcoding it as a dependency is not a good solution for the package.
I propose that we:
1. Check if the user has `next` in their `package.json`.
   1. If they don't: continue doing as we currently do.
   1. If they do:
      1. Nextjs ~12: print a warning to console stating that the current Next version is not supported, and use the latest `next` version instead (e.g. 13.4.6)
      2. Nextjs ~13: do nothing, as it should work fine. continue doing as we currently do.

**Comment by YewTreeWeb** [comment]
I'm also having this issue and I've tried updating to Next 14.0.2 but I'm still getting the error 404. I keep trying multiple pages after the localhost:3000 but nothing. At the moment nothing seems to be working

**Comment by NiklasPor** [comment]
I just did a clean `pnpm create email` and ran into exactly this error. Seems like this might be due to Next 14 beeing installed? 🤔

**Comment by gabrielmfern** [comment]
Seems to me this has been since resolved as of the 2.0 for the CLI as we don't have the `.react-email` for this anymore and should avoid that. If you experience this please let me know and I'll reopen.
