### ISSUE TITLE
Preview Mode breaks

### ISSUE THREAD

**Issue by kleenkanteen** [resend/react-email#848]
### Describe the Bug

Same issue as #613.

Error message:
![image](https://github.com/resendlabs/react-email/assets/67878058/ea19e24c-52fb-4786-a135-af9ae2782ab7)

### Link to the code that reproduces this issue

https://github.com/lukevella/rallly

### To Reproduce

On windows 10/11, follow the development guide in https://github.com/lukevella/rallly. At `yarn dev`, you will hit that issue.

### Expected Behavior

No error message.

### What's your node version? (if relevant)

18.16.0

**Comment by kleenkanteen** [comment]
Same issue happens on a Kubuntu VM inside virtualbox:

![image](https://github.com/resendlabs/react-email/assets/67878058/395a36ad-246a-4dab-ae50-41b255f5ae47)

**Comment by kleenkanteen** [comment]
Downgrading react-email in rallly/packages/emails/package.json to [1.7.15](https://www.npmjs.com/package/react-email/v/1.7.15) resolves the error on Kubuntu. Haven't tried windows 10.

**Comment by kimjisena** [comment]
> On Windows 10 it first creates an `emails` folder with the example emails in the root, but doesn't copy it inside the generated `.react-email` so it breaks... After manually moving the `emails` it inside `.react-email` all works well.

@zanzlender did you move the whole `emails` folder into `.react-email` or you copied each individual file?

**Comment by zanzlender** [comment]
> > On Windows 10 it first creates an `emails` folder with the example emails in the root, but doesn't copy it inside the generated `.react-email` so it breaks... After manually moving the `emails` it inside `.react-email` all works well.
> 
> @zanzlender did you move the whole `emails` folder into `.react-email` or you copied each individual file?

I just copied the whole folder

**Comment by gabrielmfern** [comment]
This should not happen the same as of `react-email@2.0.0` and should now be fixed.

Check the [changelog](https://react.email/docs/changelog#jan-19-2024) and our [blog post](https://resend.com/blog/react-email-2) for more info on this.
