### ISSUE TITLE
Support email client images open twice when zooming on them by clicking

### ISSUE THREAD

**Issue by sina-salahshour** [resend/react-email#867]
### Describe the Bug

on website docs, when clicking images of support snippets (for example last section of `https://react.email/docs/components/hr`).
zoom modal opens two times and for closing the modal, user has to click outside two times.

### Which package is affected (leave empty if unsure)

docs

### Link to the code that reproduces this issue

https://react.email/docs/components/hr

### To Reproduce

click on the `Gmail` icon in support snippet

### Expected Behavior

to click outside one time to close the modal.

**Comment by sina-salahshour** [comment]
i checked with another sites that use mintlify, the problem does not exist in 
https://flatfile.com/docs/guides/theming
https://docs.depict.ai/react-ui-guide/setup/product-card

if you look at the react email source, the img tag is wrapped with the modal trigger two times, and has two separate click event listeners for modals.

```html
<!-- one -->
<span aria-owns="rmiz-modal-4dd1a0087e25" data-rmiz="">
   <span data-rmiz-content="found" style="visibility: visible;">
      <!-- two -->
      <span aria-owns="rmiz-modal-7e68ea758cb8" data-rmiz="">
         <span data-rmiz-content="found" style="visibility: visible;"><img src="https://react.email/static/icons/outlook.svg" alt="Outlook" class="mx-auto mb-1" width="56px" height="56px"></span>
         <span data-rmiz-ghost="" style="height: 56px; left: 29px; width: 56px; top: 0px;">
            <button aria-label="Expand image: Outlook" data-rmiz-btn-zoom="" type="button">
               <svg aria-hidden="true" data-rmiz-btn-zoom-icon="true" fill="currentColor" focusable="false" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                  <path d="M 9 1 L 9 2 L 12.292969 2 L 2 12.292969 L 2 9 L 1 9 L 1 14 L 6 14 L 6 13 L 2.707031 13 L 13 2.707031 L 13 6 L 14 6 L 14 1 Z"></path>
               </svg>
            </button>
         </span>
      </span>
   </span>
   <span data-rmiz-ghost="" style="height: 56px; left: 29px; width: 56px; top: 0px;">
      <button aria-label="Expand image: Outlook" data-rmiz-btn-zoom="" type="button">
         <svg aria-hidden="true" data-rmiz-btn-zoom-icon="true" fill="currentColor" focusable="false" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
            <path d="M 9 1 L 9 2 L 12.292969 2 L 2 12.292969 L 2 9 L 1 9 L 1 14 L 6 14 L 6 13 L 2.707031 13 L 13 2.707031 L 13 6 L 14 6 L 14 1 Z"></path>
         </svg>
      </button>
   </span>
</span>
<p>Outlook</p>

```

**Comment by gabrielmfern** [comment]
I think this is an issue with Mintlify though, but it only happens when having a snippet with an image inside, I tried the opposite and the issue seems to go away 🤔.

**Comment by gabrielmfern** [comment]
Going to close this as this seems to be an issue with Mintlify here. We'll talk to them.

**Comment by gabrielmfern** [comment]
Update on this, I think changing the way we use the snippets fixes it I'll get a PR out with a different file structure and this as well.
