### ISSUE TITLE
Img doesn't inherit className

### ISSUE THREAD

**Issue by xriter** [resend/react-email#888]
### Describe the Bug

When using:
```
<Img
    src="logo.jpg"
    alt="my logo"
    className="logo"
/>
```
the output is:
```
<img src="logo.jpg" alt="my logo" />
```
For some reason the className is not copied over.

### Which package is affected (leave empty if unsure)

@react-email/img

### Link to the code that reproduces this issue

-

### To Reproduce

See above

### Expected Behavior

The className should be copied over to the final element. To make custom css styling based on class names possible.

**Comment by bukinoshita** [comment]
Is this happening only with Tailwing?

**Comment by promisetochi** [comment]
#923 Should fix this

**Comment by AravindGuna123** [comment]
Can I work on this ?

**Comment by gabrielmfern** [comment]
This has since been fixed.
