### ISSUE TITLE
Flex properties not working properly 

### ISSUE THREAD

**Issue by rtpa25** [resend/react-email#889]
### Describe the Bug

![Screenshot 2023-08-22 at 11 42 41 AM](https://github.com/resendlabs/react-email/assets/72537293/d2ff1f5c-5f1f-4aaf-87b1-2476f452333c)
As you can see the way I have mentioned display: flex, <also tried it the tailwind way>
![Screenshot 2023-08-22 at 11 40 14 AM](https://github.com/resendlabs/react-email/assets/72537293/b26e49e9-7f81-4628-8940-a78d1caffc2c) This is how it looks while developing
![Screenshot 2023-08-22 at 11 40 50 AM](https://github.com/resendlabs/react-email/assets/72537293/275bda81-110b-4057-807d-2101b0ecb818) This is how it looks in my inbox -- basically all the styles appear except the flex styling

### Link to the code that reproduces this issue

https://github.com/rtpa25/react-email-issue-minimal/blob/main/emails/premium-analysis.tsx

### To Reproduce

Just follow basic steps to start the next app 

### Expected Behavior

Should look the same in dev and prod

**Comment by lordelogos** [comment]
Hi @rtpa25,

This is not a `react-email` bug. 
As @Joeao mentioned, it has to do with the limited support of email clients for modern css properties

A useful resource you can use to check the support of your css is 
[`caniemail`](https://www.caniemail.com)

In your specific case, there is about ~60% support for `flex-direction: column` and there is no support in Gmail at all.
See screenshot below.

![Screenshot 2023-08-22 at 13 46 59](https://github.com/resendlabs/react-email/assets/67395687/e2181267-b48c-4cf5-8e7a-26b3e852f319)

**Comment by rtpa25** [comment]
Hey thanks for the clarification, This was my first time writing beautiful emails, so had no idea about this, did some research and found the same. 
Thanks for building this amazing tooling.
