### ISSUE TITLE
`Button` Ignores `padding` 

### ISSUE THREAD

**Issue by shellscape** [resend/react-email#903]
### Describe the Bug

The `Button` component ignores padding passed to the style props, and expects instead a `pX` and `pY` property. 

This is not documented, and the `ButtonProps` type does not properly remove `padding` from possible `style` props keys.  

### Which package is affected (leave empty if unsure)

@react-email/button

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email/blob/490e0356685c1a6406c89620687725d0b98ad53b/packages/button/src/button.tsx#L7-L10

### To Reproduce

No reproduction necessary since this is apparent in source. 

### Expected Behavior

Documentation should reflect the current component state, and should not allow properties that will be discarded.

### What's your node version? (if relevant)

18

**Comment by lordelogos** [comment]
Hi @shellscape,
I'm currently working on a PR to update the docs for the button component and I've updated the examples to use the correct syntax. 
I'll reference this issue in the PR. 
Thank you for bringing it up.

**Comment by gabrielmfern** [comment]
This has been fixed as of #909
