### ISSUE TITLE
Source tab of demo site examples does not match repo

### ISSUE THREAD

**Issue by scrhartley** [resend/react-email#908]
### Describe the Bug

In #901, the demo examples were refactored to use the Row component as intended. This does not seem to be reflected on the live site, so I assume that https://demo.react.email needs a redeploy.

### Which package is affected (leave empty if unsure)

demo

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email

### To Reproduce

Look at the first use of the Row component in https://github.com/resendlabs/react-email/blob/main/demo/emails/apple-receipt.tsx

```TSX
  <Html>
    <Head />
    <Preview>Apple Receipt</Preview>

    <Body style={main}>
      <Container style={container}>
        <Section>
          <Row>
            <Column>
```

See that it is missing in: https://demo.react.email/preview/apple-receipt?view=source

### Expected Behavior

The demos on the site should use the Row component and match the repo.

**Comment by gabrielmfern** [comment]
This has been since updated
