### ISSUE TITLE
Compile Error - when project is within nested folder - Error: Expected a backslash preceding the semicolon. 

### ISSUE THREAD

**Issue by jwarykowski** [resend/react-email#959]
### Describe the Bug

If you have your app within a nested folder e.g `apps`, when running `yarn dev` the application fails to compile with the following error:

```
./src/styles/globals.css.webpack[javascript/auto]!=!../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[13].use[2]!../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[13].use[3]!./src/styles/globals.css
Error: Expected a backslash preceding the semicolon.
    at resolveMatches.next (<anonymous>)
    at Function.from (<anonymous>)
    at runMicrotasks (<anonymous>)
```

Note if I pull the files into the root folder it works as expected.

### Link to the code that reproduces this issue

https://github.com/jwarykowski/react-email-nested-folder-issue

### To Reproduce

1. Download repo highlighted above
2. Navigate into `apps` folder
3. Run `yarn && yarn dev`
4. Fails to compile and error above appears

### Expected Behavior

Application bundles as expected

### What's your node version? (if relevant)

v16.10.0

**Comment by gabrielmfern** [comment]
Seems like the repro isn't public anymore, sorry for taking so long to look at this one, if you can make another one it'd be awesome!

**Comment by jwarykowski** [comment]
Hey @gabrielmfern, sorry, I've changed the visibility. I accidentally set this repo as private. If you can take another look that would be greatly appreciated.

**Comment by gabrielmfern** [comment]
So this works properly with our now `react-email@2.0.0`, if you didn't know about it here's the blog post https://resend.com/blog/react-email-2.

Here are the steps if you want to get this running properly on the env you provided:

1. Delete `yarn.lock` (had a few issues without this)
2. Add the following to your `package.json`:
    ```json
      "resolutions": {
        "strip-ansi": "^6.0.1"
      }
    ```
    From https://github.com/yarnpkg/yarn/issues/8976#issuecomment-1728116600
3. Run `yarn add react-email@latest`

Will close this as completed as it seems to be fixed as of the latest. If this still happens let me know and I'll reopen this.
