### ISSUE TITLE
error [Error: This browser does not support `document.implementation.createHTMLDocument`]

### ISSUE THREAD

**Issue by tanjunior** [resend/react-email#980]
### Describe the Bug

I am getting this error when I use @react-email/tailwind, I also tried the tailwind from @react-email/components and am getting the same error.

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/tanjunior/portfolio/tree/master/packages/email

### To Reproduce

clone project, 

go to `apps/nextjs` folder `pnpm dev`
go to `localhost:3000/new` and submit the contact form

### Expected Behavior

Receive error `[Error: This browser does not support `document.implementation.createHTMLDocument`]` on the server

**Comment by gabrielmfern** [comment]
Do you still have the problem? Tried using your project to reproduce but couldn't get things running without an env, can you get something smaller to reproduce?

**Comment by gabrielmfern** [comment]
Closing this as it is now stale, if anyone has an issue like this please comment and I'll reopen it.
