### ISSUE TITLE
 Type error: An import path cannot end with a '.tsx' extension. [when running email build]

### ISSUE THREAD

**Issue by EdPutans** [resend/react-email#987]
### Describe the Bug

When trying to run `email build`,  the output fails on the `checking validity of types stage`
```bash
info  - Linting and checking validity of types...
Failed to compile.

./emails/clientrequestone.tsx:1:18
Type error: An import path cannot end with a '.tsx' extension. Consider importing '../../emails/clientrequestone.js' instead.

> 1 | import Mail from '../../emails/clientrequestone.tsx';
```

The same happens when trying to run the build command on a fresh install of the latest (1.9.3) version.

```sh
Failed to compile.

./emails/notion-magic-link.tsx:1:18
Type error: An import path cannot end with a '.tsx' extension. Consider importing '../../emails/notion-magic-link.js' instead.

> 1 | import Mail from '../../emails/notion-magic-link.tsx';
    |                  ^
  2 | export default Mail;
error Command failed with exit code 1.
```

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/EdPutans/react-email-starter-build-failure-demo

### To Reproduce

1. clone the repo
2. run `yarn email build` or `npx email build`

(the `.react-email` folder has been kept in tact in case it helps to debug)

### Expected Behavior

The thing builds.

### What's your node version? (if relevant)

18.16.0

**Comment by nirtamir2** [comment]
I had the same issue
I added 
```ts
typescript: {
    // @see https://github.com/resendlabs/react-email/issues/987
    // Type error: An import path cannot end with a '.tsx' extension. Consider importing '../../emails/raycast-job-email.js' instead.
    ignoreBuildErrors: true
  }
```
to `.react-email/next.config.js`

**Comment by EdPutans** [comment]
That worked, thanks @nirtamir2. 
Guessing few people find value in the `build` feature considering it hasn't been raised outside here / fixed yet

**Comment by Robin-Ln** [comment]
i have the same issue : https://gitlab.com/robin.louarn/programme-tz-2023
